# Generated by scripts/sdk-gen/python.ts from api-docs/openapi.json. Do not edit.
# Models by datamodel-code-generator; constraints are stripped so parsing stays lenient.

from __future__ import annotations
from typing import Any, Dict, List, Literal, Optional
from invoice_ai._models import BaseModel


class Business(BaseModel):
    """
    Your business profile — the "From" side of every invoice.
    """

    id: str
    """
    Business id (UUID).
    """
    legal_name: str
    """
    Registered legal name, printed as the invoice issuer.
    """
    trade_name: Optional[str] = None
    """
    Trading name, if different.
    """
    country_code: str
    """
    ISO 3166-1 alpha-2 country code.
    """
    currency: str
    """
    Default invoice currency (ISO 4217).
    """
    tax_id: Optional[str] = None
    """
    Your tax registration number, free text.
    """
    address: BusinessAddress
    """
    Registered address.
    """
    email: Optional[str] = None
    """
    Contact email printed on invoices.
    """
    phone: Optional[str] = None
    """
    Contact phone.
    """
    bank: BusinessBank
    """
    Payment details printed on invoices.
    """
    invoice_prefix: str
    """
    Prefix of every invoice number, e.g. `INV` in `INV-0042`.
    """
    created_at: str
    """
    When the business profile was created (ISO 8601).
    """


class BusinessAddress(BaseModel):
    """
    Registered address.
    """

    line1: Optional[str] = None
    """
    Street address.
    """
    line2: Optional[str] = None
    """
    Suite, floor, unit.
    """
    city: Optional[str] = None
    """
    City.
    """
    region: Optional[str] = None
    """
    State, province or region.
    """
    postal_code: Optional[str] = None
    """
    ZIP or postal code.
    """
    country_code: Optional[str] = None
    """
    ISO 3166-1 alpha-2 country code.
    """
    country: Optional[str] = None
    """
    Country name.
    """


class BusinessBank(BaseModel):
    """
    Payment details printed on invoices.
    """

    bank_name: Optional[str] = None
    """
    Bank name.
    """
    account_name: Optional[str] = None
    """
    Account holder name.
    """
    account_number: Optional[str] = None
    """
    Account number (or IBAN).
    """
    routing_number: Optional[str] = None
    """
    Routing number, sort code, IFSC or SWIFT.
    """


class Customer(BaseModel):
    """
    Someone you bill. Customers are archived, never hard-deleted.
    """

    id: str
    """
    Unique identifier, `cus_…`.
    """
    object: Literal["customer"]
    """
    Always `customer`.
    """
    name: str
    """
    Full name or legal business name.
    """
    email: Optional[str] = None
    """
    Billing email, copied onto invoices for this customer — where `POST /invoices/{id}/send` delivers by default.
    """
    phone: Optional[str] = None
    """
    Phone number, free text.
    """
    tax_id: Optional[str] = None
    """
    Tax registration number (VAT, EIN, GSTIN, ABN…), free text. Printed on invoices.
    """
    address: CustomerAddress
    """
    Billing address. Every field may be null.
    """
    deleted: bool
    """
    True once archived with `DELETE /customers/{id}`. Archived customers stay readable.
    """
    created: str
    """
    When the customer was created (ISO 8601).
    """


class CustomerAddress(BaseModel):
    """
    Billing address. Every field may be null.
    """

    line1: Optional[str] = None
    """
    Street address.
    """
    line2: Optional[str] = None
    """
    Apartment, suite, unit.
    """
    city: Optional[str] = None
    """
    City or locality.
    """
    state: Optional[str] = None
    """
    State, province or region.
    """
    postal_code: Optional[str] = None
    """
    ZIP or postal code.
    """
    country: Optional[str] = None
    """
    ISO 3166-1 alpha-2 country code.
    """


class CustomerCreate(BaseModel):
    name: str
    """
    Full name or legal business name.
    """
    email: Optional[str] = None
    """
    Billing email. `POST /invoices/{id}/send` delivers here unless you pass `to`. `""` clears it.
    """
    phone: Optional[str] = None
    """
    Phone number, free text.
    """
    tax_id: Optional[str] = None
    """
    Tax registration number (VAT, EIN, GSTIN…), free text — no format check.
    """
    address: Optional[CustomerCreateAddress] = None
    """
    Billing address. Every field is optional.
    """


class CustomerCreateAddress(BaseModel):
    """
    Billing address. Every field is optional.
    """

    line1: Optional[str] = None
    """
    Street address.
    """
    line2: Optional[str] = None
    """
    Apartment, suite, unit.
    """
    city: Optional[str] = None
    """
    City or locality.
    """
    state: Optional[str] = None
    """
    State, province or region.
    """
    postal_code: Optional[str] = None
    """
    ZIP or postal code.
    """
    country: Optional[str] = None
    """
    ISO 3166-1 alpha-2 country code (uppercased for you).
    """


class CustomerUpdate(BaseModel):
    """
    Any subset of the create fields. Omitted fields are left unchanged.
    """

    name: Optional[str] = None
    """
    Full name or legal business name.
    """
    email: Optional[str] = None
    """
    Billing email. `POST /invoices/{id}/send` delivers here unless you pass `to`. `""` clears it.
    """
    phone: Optional[str] = None
    """
    Phone number, free text.
    """
    tax_id: Optional[str] = None
    """
    Tax registration number (VAT, EIN, GSTIN…), free text — no format check.
    """
    address: Optional[CustomerUpdateAddress] = None
    """
    Billing address. Every field is optional.
    """


class CustomerUpdateAddress(BaseModel):
    """
    Billing address. Every field is optional.
    """

    line1: Optional[str] = None
    """
    Street address.
    """
    line2: Optional[str] = None
    """
    Apartment, suite, unit.
    """
    city: Optional[str] = None
    """
    City or locality.
    """
    state: Optional[str] = None
    """
    State, province or region.
    """
    postal_code: Optional[str] = None
    """
    ZIP or postal code.
    """
    country: Optional[str] = None
    """
    ISO 3166-1 alpha-2 country code (uppercased for you).
    """


class Invoice(BaseModel):
    """
    An invoice: a draft, or a numbered document once finalized.
    """

    id: str
    """
    Unique identifier, `in_…`.
    """
    object: Literal["invoice"]
    """
    Always `invoice`.
    """
    number: Optional[str] = None
    """
    The invoice number, e.g. `INV-0042` (your prefix + a zero-padded counter). `null` until finalized — a draft has no number because none was spent on it.
    """
    status: Literal["draft", "open", "paid", "overdue", "void"]
    """
    `draft` → `open` (finalize) → `paid` (pay) or `void`. `overdue` is an open invoice past `due_date`; it is derived at read time and never stored.
    """
    customer: Optional[str] = None
    """
    The billed customer, `cus_…`.
    """
    currency: str
    """
    ISO 4217 currency code. Defaults to your business currency.
    """
    collection_method: Literal["charge_automatically", "send_invoice"]
    """
    How you intend to collect. Informational today; defaults to `send_invoice`.
    """
    issue_date: str
    """
    Issue date (ISO 8601 date). Set to the creation date.
    """
    due_date: Optional[str] = None
    """
    Due date (ISO 8601 date), or `null`.
    """
    description: Optional[str] = None
    """
    Notes printed on the invoice.
    """
    footer: Optional[str] = None
    """
    Terms printed at the foot of the invoice.
    """
    subtotal: int
    """
    Sum of quantity × unit_amount over all lines, before discount and tax. Integer minor units of the currency (`250000` is $2,500.00; ¥5,000 is `5000`).
    """
    discount: int
    """
    Total discount across lines. Integer minor units of the currency (`250000` is $2,500.00; ¥5,000 is `5000`).
    """
    taxable: int
    """
    `subtotal` − `discount`. Integer minor units of the currency (`250000` is $2,500.00; ¥5,000 is `5000`).
    """
    tax: int
    """
    Total tax across lines. Integer minor units of the currency (`250000` is $2,500.00; ¥5,000 is `5000`).
    """
    total: int
    """
    `taxable` + `tax`. Integer minor units of the currency (`250000` is $2,500.00; ¥5,000 is `5000`).
    """
    amount_due: int
    """
    What is still owed: `total` while `open` or `overdue`, otherwise 0. Integer minor units of the currency (`250000` is $2,500.00; ¥5,000 is `5000`).
    """
    amount_in_words: Optional[str] = None
    """
    The total spelled out, as printed on the PDF.
    """
    public_url_token: str
    """
    Token of the public share link (`/i/{token}`). Anyone with it can view the invoice.
    """
    finalized_at: Optional[str] = None
    """
    When the invoice was finalized, or `null`.
    """
    paid_at: Optional[str] = None
    """
    When the invoice was marked paid, or `null`.
    """
    voided_at: Optional[str] = None
    """
    When the invoice was voided, or `null`.
    """
    void_reason: Optional[str] = None
    """
    The reason given to `POST /invoices/{id}/void`.
    """
    created: str
    """
    When the invoice was created (ISO 8601).
    """
    updated: str
    """
    When the invoice was last changed (ISO 8601).
    """
    lines: Optional[InvoiceLines] = None
    """
    The invoice lines. Included when reading or writing a single invoice; omitted from list results and from the pay and void responses.
    """


class InvoiceCreate(BaseModel):
    customer: str
    """
    The customer to bill, `cus_…` or UUID. Must already exist (`POST /customers`).
    """
    currency: Optional[str] = None
    """
    ISO 4217 code. Defaults to your business currency.
    """
    collection_method: Optional[Literal["charge_automatically", "send_invoice"]] = None
    """
    Defaults to `send_invoice`. Informational today.
    """
    due_date: Optional[str] = None
    """
    Due date, `YYYY-MM-DD`. `""` clears it.
    """
    days_until_due: Optional[int] = None
    """
    Alternative to `due_date` on create only: issue date + N days (0–365). Ignored on update.
    """
    description: Optional[str] = None
    """
    Notes printed on the invoice.
    """
    footer: Optional[str] = None
    """
    Terms printed at the foot of the invoice.
    """
    items: Optional[List[InvoiceLineInput]] = None
    """
    The lines, at least one. On update, replaces every existing line; omit to keep them.
    """


class InvoiceEvent(BaseModel):
    """
    One entry in an invoice’s history. The same names are used for webhook events.
    """

    id: str
    """
    Event id (UUID).
    """
    type: Literal[
        "invoice.created",
        "invoice.updated",
        "invoice.finalized",
        "invoice.emailed",
        "invoice.email_failed",
        "invoice.viewed",
        "invoice.downloaded",
        "invoice.paid",
        "invoice.voided",
    ]
    """
    What happened. `invoice.viewed` and `invoice.downloaded` are recorded when the customer opens the public share link.
    """
    meta: Optional[Dict[str, Any]] = None
    """
    Context: `actor`, `request_id`, `api_key_id`, and event-specific fields such as `to`, `reason` or `reference`.
    """
    created_at: str
    """
    When it happened (ISO 8601).
    """


class InvoiceItem(BaseModel):
    """
    One line of an invoice. Totals are always recomputed server-side from the lines.
    """

    id: str
    """
    Unique identifier, `ii_…`. Lines get new ids whenever the draft is re-saved.
    """
    object: Literal["invoiceitem"]
    """
    Always `invoiceitem`.
    """
    price: Optional[str] = None
    """
    The `price_…` this line was billed from, or `null` for an ad-hoc line.
    """
    product: Optional[str] = None
    """
    The price's product, `prod_…`, or `null`.
    """
    description: str
    """
    What is being billed. Defaults to the product name on priced lines.
    """
    quantity: float
    """
    Quantity, greater than zero. May be fractional.
    """
    unit: str
    """
    Unit of measure: `NOS`, `PCS`, `KGS`, `GMS`, `LTR`, `MTR`, `SQF`, `SQM`, `HRS`, `DAY`, `MON`, `BOX`, `SET`, `OTH`.
    """
    unit_amount: int
    """
    Price per unit. Integer minor units of the currency (`250000` is $2,500.00; ¥5,000 is `5000`).
    """
    amount: int
    """
    Line total after discount, including tax. Integer minor units of the currency (`250000` is $2,500.00; ¥5,000 is `5000`).
    """
    discount_percent: float
    """
    Discount percentage (0–100) applied before tax.
    """
    tax_rate: float
    """
    Tax percentage (0–100), exclusive — added on top of the discounted amount.
    """
    tax_amount: int
    """
    Tax on this line. Integer minor units of the currency (`250000` is $2,500.00; ¥5,000 is `5000`).
    """


class InvoiceItemCreate(BaseModel):
    """
    Either `price`, or `description` + `unit_amount`.
    """

    price: Optional[str] = None
    """
    A catalog price, `price_…` or UUID. Its product name, unit amount and tax rate fill any of `description`, `unit_amount`, `tax_rate` you omit. Its currency must match the invoice.
    """
    description: Optional[str] = ""
    """
    What you are billing for. Required unless `price` is given.
    """
    quantity: Optional[float] = 1
    """
    Quantity, greater than zero. Defaults to 1.
    """
    unit: Optional[
        Literal["NOS", "PCS", "KGS", "GMS", "LTR", "MTR", "SQF", "SQM", "HRS", "DAY", "MON", "BOX", "SET", "OTH"]
    ] = "NOS"
    """
    Unit of measure. Defaults to `NOS` (numbers).
    """
    unit_amount: Optional[int] = None
    """
    Price per unit in integer minor units of the invoice currency. Required unless `price` is given.
    """
    discount_percent: Optional[float] = 0
    """
    Discount percentage, 0–100, applied before tax. Defaults to 0.
    """
    tax_rate: Optional[float] = None
    """
    Tax percentage, 0–100, added on top. Defaults to the price’s rate, or 0 on ad-hoc lines.
    """
    invoice: str
    """
    The draft to append to, `in_…` or UUID.
    """


class InvoiceLineInput(BaseModel):
    """
    Either `price`, or `description` + `unit_amount`.
    """

    price: Optional[str] = None
    """
    A catalog price, `price_…` or UUID. Its product name, unit amount and tax rate fill any of `description`, `unit_amount`, `tax_rate` you omit. Its currency must match the invoice.
    """
    description: Optional[str] = ""
    """
    What you are billing for. Required unless `price` is given.
    """
    quantity: Optional[float] = 1
    """
    Quantity, greater than zero. Defaults to 1.
    """
    unit: Optional[
        Literal["NOS", "PCS", "KGS", "GMS", "LTR", "MTR", "SQF", "SQM", "HRS", "DAY", "MON", "BOX", "SET", "OTH"]
    ] = "NOS"
    """
    Unit of measure. Defaults to `NOS` (numbers).
    """
    unit_amount: Optional[int] = None
    """
    Price per unit in integer minor units of the invoice currency. Required unless `price` is given.
    """
    discount_percent: Optional[float] = 0
    """
    Discount percentage, 0–100, applied before tax. Defaults to 0.
    """
    tax_rate: Optional[float] = None
    """
    Tax percentage, 0–100, added on top. Defaults to the price’s rate, or 0 on ad-hoc lines.
    """


class InvoiceLines(BaseModel):
    """
    The invoice lines. Included when reading or writing a single invoice; omitted from list results and from the pay and void responses.
    """

    data: List[InvoiceItem]
    """
    The lines, in order.
    """


class InvoicePay(BaseModel):
    paid_on: Optional[str] = None
    """
    When payment was received (ISO 8601 date or timestamp). Defaults to now.
    """
    reference: Optional[str] = None
    """
    Your payment reference (cheque number, bank transfer id). Recorded on the `invoice.paid` event.
    """


class InvoiceSend(BaseModel):
    to: Optional[str] = None
    """
    Recipient email. Defaults to the customer email recorded on the invoice; one of the two is required.
    """


class InvoiceSendResponse(BaseModel):
    data: Invoice
    """
    The invoice, finalized if it was a draft, with lines.
    """
    emailed_to: str
    """
    The address the email was sent to: `to`, or the customer email.
    """


class InvoiceUpdate(BaseModel):
    """
    Any subset of fields. Omitted fields keep their stored value; omit `items` to keep the lines.
    """

    customer: Optional[str] = None
    """
    Bill a different customer, `cus_…` or UUID. Omit to keep the current one.
    """
    currency: Optional[str] = None
    """
    ISO 4217 code. Defaults to your business currency.
    """
    collection_method: Optional[Literal["charge_automatically", "send_invoice"]] = None
    """
    Defaults to `send_invoice`. Informational today.
    """
    due_date: Optional[str] = None
    """
    Due date, `YYYY-MM-DD`. `""` clears it.
    """
    days_until_due: Optional[int] = None
    """
    Alternative to `due_date` on create only: issue date + N days (0–365). Ignored on update.
    """
    description: Optional[str] = None
    """
    Notes printed on the invoice.
    """
    footer: Optional[str] = None
    """
    Terms printed at the foot of the invoice.
    """
    items: Optional[List[InvoiceLineInput]] = None
    """
    The lines, at least one. On update, replaces every existing line; omit to keep them.
    """


class InvoiceVoid(BaseModel):
    reason: str
    """
    Why the invoice is void. Required and non-blank; stored as `void_reason`.
    """


class Price(BaseModel):
    """
    One way to charge for a product: an amount in a currency, one-time or recurring.
    """

    id: str
    """
    Unique identifier, `price_…`.
    """
    object: Literal["price"]
    """
    Always `price`.
    """
    product: Optional[str] = None
    """
    The parent product, `prod_…`. Cannot change after creation.
    """
    nickname: Optional[str] = None
    """
    Internal label, e.g. "Monthly".
    """
    unit_amount: int
    """
    Price per unit. Integer minor units of the currency (`250000` is $2,500.00; ¥5,000 is `5000`).
    """
    currency: str
    """
    ISO 4217 currency code, uppercase.
    """
    billing_scheme: Literal["per_unit"]
    """
    Always `per_unit`.
    """
    type: Literal["one_time", "recurring"]
    """
    `recurring` prices carry `recurring`; nothing auto-bills them yet.
    """
    recurring: Optional[PriceRecurring] = None
    """
    Billing cadence. `null` on one-time prices.
    """
    tax_rate: float
    """
    Default tax percentage (0–100) for lines billed from this price.
    """
    active: bool
    """
    `false` once archived. Archived prices cannot be chosen for new lines in the app.
    """
    created: str
    """
    When the price was created (ISO 8601).
    """


class PriceCreate(BaseModel):
    product: str
    """
    The parent product, `prod_…` or UUID.
    """
    nickname: Optional[str] = None
    """
    Internal label, e.g. "Monthly".
    """
    unit_amount: int
    """
    Price per unit in integer minor units (`2500000` is $25,000.00).
    """
    currency: str
    """
    ISO 4217 code, three letters (uppercased for you). Must match the invoice currency when billed.
    """
    type: Optional[Literal["one_time", "recurring"]] = "one_time"
    """
    `one_time` (default) or `recurring`. `recurring` requires `recurring.interval`.
    """
    recurring: Optional[PriceCreateRecurring] = None
    """
    Required when `type` is `recurring`; must be omitted for `one_time`.
    """
    tax_rate: Optional[float] = 0
    """
    Default tax percentage, 0–100, for lines billed from this price. Defaults to 0.
    """
    active: Optional[bool] = True
    """
    Whether the price is available. Defaults to `true`.
    """


class PriceCreateRecurring(BaseModel):
    """
    Required when `type` is `recurring`; must be omitted for `one_time`.
    """

    interval: Literal["day", "week", "month", "year"]
    """
    Billing interval: `day`, `week`, `month`, `year`.
    """
    interval_count: Optional[int] = 1
    """
    Intervals between bills, 1–52. Defaults to 1.
    """


class PriceRecurring(BaseModel):
    interval: Optional[str] = None
    """
    `day`, `week`, `month` or `year`.
    """
    interval_count: int
    """
    Number of intervals between bills (1–52).
    """


class PriceUpdate(BaseModel):
    """
    Any subset of fields. Omitted fields are left unchanged.
    """

    product: Optional[str] = None
    """
    Not updatable — sending it is a `422`. Create a new price on the other product instead.
    """
    nickname: Optional[str] = None
    """
    Internal label. `null` or `""` clears it.
    """
    unit_amount: Optional[int] = None
    """
    Price per unit in integer minor units (`2500000` is $25,000.00).
    """
    currency: Optional[str] = None
    """
    ISO 4217 code, three letters (uppercased for you). Must match the invoice currency when billed.
    """
    type: Optional[Literal["one_time", "recurring"]] = None
    """
    Switching to `one_time` clears the interval; switching to `recurring` needs `recurring.interval` unless one is stored.
    """
    recurring: Optional[PriceUpdateRecurring] = None
    """
    Required when `type` is `recurring`; must be omitted for `one_time`.
    """
    tax_rate: Optional[float] = None
    """
    Default tax percentage, 0–100, for lines billed from this price. Defaults to 0.
    """
    active: Optional[bool] = None
    """
    `false` archives, `true` restores.
    """


class PriceUpdateRecurring(BaseModel):
    """
    Required when `type` is `recurring`; must be omitted for `one_time`.
    """

    interval: Literal["day", "week", "month", "year"]
    """
    Billing interval: `day`, `week`, `month`, `year`.
    """
    interval_count: Optional[int] = 1
    """
    Intervals between bills, 1–52. Defaults to 1.
    """


class Problem(BaseModel):
    """
    An RFC 9457 problem details object, served as `application/problem+json`. Every non-2xx response uses this shape.
    """

    type: str
    """
    A URI identifying the problem type: `https://invoice.horizonpay.co/problems/<code>` with underscores as hyphens.
    """
    title: str
    """
    Short, human-readable summary of the problem type.
    """
    status: int
    """
    The HTTP status code, repeated for convenience.
    """
    detail: str
    """
    Human-readable explanation of this occurrence. Wording may change — do not parse it.
    """
    instance: str
    """
    The request id (also sent as `X-Request-Id`), for correlating with our logs.
    """
    code: str
    """
    Stable machine-readable code. Branch on this, never on `detail`. One of: `validation`, `idempotency_mismatch`, `unauthorized`, `forbidden`, `not_found`, `invalid_state`, `conflict`, `idempotency_key_required`, `rate_limited`, `upstream_failed`, `internal_error`.
    """
    errors: Optional[List[ProblemErrorsItem]] = None
    """
    Field-level problems. Present on `validation` errors only.
    """


class ProblemErrorsItem(BaseModel):
    path: str
    """
    Dot-path of the offending field, e.g. `items.0.unit_amount`.
    """
    message: str
    """
    What is wrong with it.
    """


class Product(BaseModel):
    """
    Something you sell. Money lives on its prices, not on the product.
    """

    id: str
    """
    Unique identifier, `prod_…`.
    """
    object: Literal["product"]
    """
    Always `product`.
    """
    name: str
    """
    Shown as the line description when a price of this product is billed.
    """
    description: Optional[str] = None
    """
    Longer description for your own reference.
    """
    images: List[str]
    """
    Up to 8 image URLs.
    """
    active: bool
    """
    `false` once archived. Archived products keep their prices and history.
    """
    created: str
    """
    When the product was created (ISO 8601).
    """
    updated: str
    """
    When the product was last changed (ISO 8601).
    """


class ProductCreate(BaseModel):
    name: str
    """
    Product name, 1–200 characters. Becomes the default line description.
    """
    description: Optional[str] = None
    """
    Longer description.
    """
    images: Optional[List[str]] = []
    """
    Up to 8 image URLs.
    """
    active: Optional[bool] = True
    """
    Whether the product is available. Defaults to `true` on create.
    """


class ProductUpdate(BaseModel):
    """
    Any subset of fields. Omitted fields are left unchanged.
    """

    name: Optional[str] = None
    """
    Product name, 1–200 characters. Becomes the default line description.
    """
    description: Optional[str] = None
    """
    Longer description. `null` or `""` clears it.
    """
    images: Optional[List[str]] = None
    """
    Up to 8 image URLs.
    """
    active: Optional[bool] = None
    """
    `false` archives, `true` restores.
    """


class WebhookEndpoint(BaseModel):
    """
    A URL that receives signed invoice events (Standard Webhooks format).
    """

    id: str
    """
    Endpoint id (UUID).
    """
    url: str
    """
    The https URL deliveries are POSTed to.
    """
    events: List[
        Literal[
            "invoice.created",
            "invoice.updated",
            "invoice.finalized",
            "invoice.emailed",
            "invoice.email_failed",
            "invoice.viewed",
            "invoice.downloaded",
            "invoice.paid",
            "invoice.voided",
        ]
    ]
    """
    Subscribed event types. An endpoint registered with no events receives every type, and lists them all here.
    """
    active: bool
    """
    `false` once deliveries are disabled, which happens after 20 consecutive failures.
    """
    disabled_at: Optional[str] = None
    """
    When deliveries were disabled, or `null`.
    """
    failure_count: int
    """
    Consecutive failed deliveries.
    """
    created_at: str
    """
    When the endpoint was registered (ISO 8601).
    """


class WebhookEndpointCreate(BaseModel):
    url: str
    """
    An `https://` URL that does not resolve to a private, loopback or link-local address.
    """
    events: Optional[
        List[
            Literal[
                "invoice.created",
                "invoice.updated",
                "invoice.finalized",
                "invoice.emailed",
                "invoice.email_failed",
                "invoice.viewed",
                "invoice.downloaded",
                "invoice.paid",
                "invoice.voided",
            ]
        ]
    ] = None
    """
    Event types to receive. Omit or send `[]` to receive every type, including ones added later.
    """


class WebhookEndpointCreateResult(BaseModel):
    """
    The created endpoint, including its secret.
    """

    id: str
    """
    Endpoint id (UUID).
    """
    url: str
    """
    The https URL deliveries are POSTed to.
    """
    events: List[
        Literal[
            "invoice.created",
            "invoice.updated",
            "invoice.finalized",
            "invoice.emailed",
            "invoice.email_failed",
            "invoice.viewed",
            "invoice.downloaded",
            "invoice.paid",
            "invoice.voided",
        ]
    ]
    """
    Subscribed event types. An endpoint registered with no events receives every type, and lists them all here.
    """
    active: bool
    """
    `false` once deliveries are disabled, which happens after 20 consecutive failures.
    """
    disabled_at: Optional[str] = None
    """
    When deliveries were disabled, or `null`.
    """
    failure_count: int
    """
    Consecutive failed deliveries.
    """
    created_at: str
    """
    When the endpoint was registered (ISO 8601).
    """
    secret: str
    """
    Signing secret for verifying `webhook-signature`: `whsec_` followed by standard base64 (Standard Webhooks). Returned only in this response.
    """
