# Generated by scripts/sdk-gen/python.ts from api-docs/openapi.json. Do not edit.

"""TypedDicts for nested request objects: pass plain dicts shaped like these (or the matching models)."""

from __future__ import annotations

from typing_extensions import Literal, Required, TypedDict

__all__ = ["CustomerCreateAddressParam", "CustomerUpdateAddressParam", "InvoiceLineInputParam", "PriceCreateRecurringParam", "PriceUpdateRecurringParam"]


class CustomerCreateAddressParam(TypedDict, total=False):
    """Billing address. Every field is optional."""

    line1: str
    """Street address."""

    line2: str
    """Apartment, suite, unit."""

    city: str
    """City or locality."""

    state: str
    """State, province or region."""

    postal_code: str
    """ZIP or postal code."""

    country: str
    """ISO 3166-1 alpha-2 country code (uppercased for you)."""


class CustomerUpdateAddressParam(TypedDict, total=False):
    """Billing address. Every field is optional."""

    line1: str
    """Street address."""

    line2: str
    """Apartment, suite, unit."""

    city: str
    """City or locality."""

    state: str
    """State, province or region."""

    postal_code: str
    """ZIP or postal code."""

    country: str
    """ISO 3166-1 alpha-2 country code (uppercased for you)."""


class InvoiceLineInputParam(TypedDict, total=False):
    """Either `price`, or `description` + `unit_amount`."""

    price: str
    """A catalog price, `price_…` or UUID. Its product name, unit amount and tax rate fill any of `description`, `unit_amount`, `tax_rate` you omit. Its currency must match the invoice."""

    description: str
    """What you are billing for. Required unless `price` is given."""

    quantity: float
    """Quantity, greater than zero. Defaults to 1."""

    unit: Literal["NOS", "PCS", "KGS", "GMS", "LTR", "MTR", "SQF", "SQM", "HRS", "DAY", "MON", "BOX", "SET", "OTH"]
    """Unit of measure. Defaults to `NOS` (numbers)."""

    unit_amount: int
    """Price per unit in integer minor units of the invoice currency. Required unless `price` is given."""

    discount_percent: float
    """Discount percentage, 0–100, applied before tax. Defaults to 0."""

    tax_rate: float
    """Tax percentage, 0–100, added on top. Defaults to the price’s rate, or 0 on ad-hoc lines."""


class PriceCreateRecurringParam(TypedDict, total=False):
    """Required when `type` is `recurring`; must be omitted for `one_time`."""

    interval: Required[Literal["day", "week", "month", "year"]]
    """Billing interval: `day`, `week`, `month`, `year`."""

    interval_count: int
    """Intervals between bills, 1–52. Defaults to 1."""


class PriceUpdateRecurringParam(TypedDict, total=False):
    """Required when `type` is `recurring`; must be omitted for `one_time`."""

    interval: Required[Literal["day", "week", "month", "year"]]
    """Billing interval: `day`, `week`, `month`, `year`."""

    interval_count: int
    """Intervals between bills, 1–52. Defaults to 1."""
