/**
 * Generates the Python SDK (packages/sdk-python) from api-docs/openapi.json.
 *
 *   pnpm sdk:gen        (runs ts.ts, then this)
 *
 * Writes, under packages/sdk-python/invoice_ai:
 *   types/_generated.py   Pydantic v2 models, by datamodel-code-generator (needs `uv`)
 *   types/params.py       TypedDicts for nested request objects (InvoiceLineInputParam…)
 *   types/__init__.py     public re-exports
 *   resources/<name>.py   one sync + one async class per tag, plus their .with_raw_response views
 *   resources/__init__.py re-exports and the resource-carrying client bases
 *   _operations.py        operationId → resource.method manifest (tests use it)
 *   _meta.py              API version from info.version
 *
 * Model generation runs datamodel-code-generator through `uv run` in the
 * package's own environment (pinned in uv.lock). Without uv it is skipped with
 * a warning, and everything else is still regenerated.
 *
 * Never edit those files by hand; change the spec or this script and rerun.
 */
import { spawnSync } from 'node:child_process'
import { mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync, existsSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { deref, loadSpec, refName, type Json, type SpecOperation, type SpecResource } from './spec'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const SPEC = join(ROOT, 'api-docs', 'openapi.json')
const PKG = join(ROOT, 'packages', 'sdk-python')
const SRC = join(PKG, 'invoice_ai')
const HEADER = '# Generated by scripts/sdk-gen/python.ts from api-docs/openapi.json. Do not edit.\n'

const spec = loadSpec(SPEC)
const raw = spec.raw

const pascal = (s: string) => s.charAt(0).toUpperCase() + s.slice(1)
const pascalWords = (s: string) => s.split(/[^A-Za-z0-9]+/).filter(Boolean).map(pascal).join('')
const snake = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase()
const clone = <T>(v: T): T => JSON.parse(JSON.stringify(v)) as T

const PY_KEYWORDS = new Set(
  'False None True and as assert async await break class continue def del elif else except finally for from global if import in is lambda nonlocal not or pass raise return try while with yield'.split(
    ' ',
  ),
)
/** Keyword-only request options every method takes; spec params may not collide with them. */
const RESERVED = new Set(['self', 'idempotency_key', 'timeout', 'max_retries', 'extra_headers'])

const pyIdent = (name: string) => (PY_KEYWORDS.has(name) ? `${name}_` : name)

/** `del` is a keyword in Python; everything else is the TS name in snake_case. */
function pyMethod(op: SpecOperation): string {
  return pyIdent(op.sdkMethod === 'del' ? 'delete' : snake(op.sdkMethod))
}

/** Same stem as the TS SDK's type names (InvoiceSend…), so both SDKs name inline shapes alike. */
function typeStem(op: SpecOperation): string {
  return op.resource.singular + pascal(op.sdkMethod === 'del' ? 'delete' : op.sdkMethod)
}

// ---------------------------------------------------------------------------
// 1. The schema set the models are generated from.
// ---------------------------------------------------------------------------

const schemas: Record<string, Json> = clone((raw.components as Json).schemas as Record<string, Json>)

/** The model each operation returns (or pages over), by name. */
const returnModel = new Map<string, string>()

for (const op of spec.operations) {
  const opRaw = ((raw.paths as Json)[op.path] as Json)[op.method.toLowerCase()] as Json
  const response = deref(raw, (opRaw.responses as Json)[String(op.successStatus)])
  const body = ((response.content as Json | undefined)?.['application/json'] as Json | undefined)?.schema
  if (op.kind === 'void' || op.kind === 'binary' || !body) continue
  const stem = typeStem(op)
  if (op.kind === 'body') {
    const name = refName(body) ?? `${stem}Response`
    if (!refName(body)) schemas[name] = clone(body as Json)
    returnModel.set(op.operationId, name)
    continue
  }
  if (op.dataRef) {
    returnModel.set(op.operationId, op.dataRef)
    continue
  }
  // Inline `data` (or inline page items): give it the same name the TS SDK uses.
  const data = deref(raw, deref(raw, body).properties && (deref(raw, body).properties as Json).data)
  const shape = op.kind === 'page' ? deref(raw, data.items) : data
  const name = `${stem}${op.kind === 'page' ? 'Item' : 'Result'}`
  schemas[name] = clone(shape)
  returnModel.set(op.operationId, name)
}

const isObjectSchema = (s: Json | undefined) => !!s && s.type === 'object' && typeof s.properties === 'object'

/** Moves inline objects into named schemas (`Customer.address` → `CustomerAddress`) so models get readable names. */
function hoist(): void {
  const visit = (node: Json, suggested: string): Json => {
    if (!node || typeof node !== 'object' || node.$ref) return node
    if (isObjectSchema(node)) {
      let name = suggested
      for (let i = 2; schemas[name] && schemas[name] !== node; i++) name = `${suggested}${i}`
      schemas[name] = node
      walk(name, node)
      const out: Json = { $ref: `#/components/schemas/${name}` }
      if (typeof node.description === 'string') out.description = node.description
      return out
    }
    for (const key of ['anyOf', 'oneOf', 'allOf'] as const) {
      if (Array.isArray(node[key])) node[key] = (node[key] as Json[]).map((m) => visit(m, suggested))
    }
    if (node.type === 'array' && node.items) node.items = visit(node.items as Json, `${suggested}Item`)
    return node
  }
  const walk = (name: string, schema: Json) => {
    const props = (schema.properties ?? {}) as Record<string, Json>
    for (const [prop, ps] of Object.entries(props)) props[prop] = visit(ps, name + pascalWords(prop))
  }
  for (const name of Object.keys(schemas)) walk(name, schemas[name]!)
}
hoist()

// ---------------------------------------------------------------------------
// 2. Pydantic models via datamodel-code-generator.
// ---------------------------------------------------------------------------

/** Constraints are the server's to enforce; the SDK parses leniently so new values never break old clients. */
const STRIP = new Set([
  'pattern',
  'minLength',
  'maxLength',
  'minimum',
  'maximum',
  'exclusiveMinimum',
  'exclusiveMaximum',
  'minItems',
  'maxItems',
  'format',
  'examples',
  'example',
  'propertyNames',
])

function lenient(node: unknown): unknown {
  if (Array.isArray(node)) return node.map(lenient)
  if (!node || typeof node !== 'object') return node
  const out: Json = {}
  for (const [k, v] of Object.entries(node as Json)) {
    if (STRIP.has(k)) continue
    if (k === 'additionalProperties' && v === false) continue
    out[k] = k === 'properties' ? Object.fromEntries(Object.entries(v as Json).map(([pk, pv]) => [pk, lenient(pv)])) : lenient(v)
  }
  return out
}

function generateModels(): void {
  const uv = spawnSync('uv', ['--version'], { encoding: 'utf8' })
  if (uv.status !== 0) {
    console.warn('  ! uv not found: skipped invoice_ai/types/_generated.py (install uv to regenerate the Python models)')
    return
  }
  const dir = mkdtempSync(join(tmpdir(), 'invoice-ai-sdk-gen-'))
  const input = join(dir, 'schemas.json')
  const doc = {
    openapi: '3.1.0',
    info: { title: spec.title, version: spec.version },
    paths: {},
    components: { schemas: lenient(schemas) },
  }
  writeFileSync(input, JSON.stringify(doc, null, 2))
  const out = join(SRC, 'types', '_generated.py')
  const args = [
    'run',
    '--project',
    PKG,
    '--frozen',
    '--quiet',
    'datamodel-codegen',
    '--input',
    input,
    '--input-file-type',
    'openapi',
    '--output',
    out,
    '--output-model-type',
    'pydantic_v2.BaseModel',
    '--base-class',
    'invoice_ai._models.BaseModel',
    '--target-python-version',
    '3.9',
    '--enum-field-as-literal',
    'all',
    '--use-schema-description',
    '--use-field-description',
    '--use-double-quotes',
    '--keep-model-order',
    '--disable-timestamp',
    '--formatters',
    'ruff-format',
    '--custom-file-header',
    `${HEADER.trim()}\n# Models by datamodel-code-generator; constraints are stripped so parsing stays lenient.`,
  ]
  const res = spawnSync('uv', args, { cwd: PKG, encoding: 'utf8' })
  rmSync(dir, { recursive: true, force: true })
  if (res.status !== 0) {
    console.error(res.stdout, res.stderr)
    throw new Error('sdk-gen: datamodel-codegen failed')
  }
  console.log(`  wrote ${out.slice(ROOT.length + 1)}`)
}

// ---------------------------------------------------------------------------
// 3. Python types for request params.
// ---------------------------------------------------------------------------

const paramTypedDicts = new Set<string>()
/** While typing a method's keyword arguments, nested objects also accept the matching model. */
let acceptModels = false

function literal(v: unknown): string {
  if (typeof v === 'string') return JSON.stringify(v)
  if (typeof v === 'boolean') return v ? 'True' : 'False'
  if (v === null) return 'None'
  return String(v)
}

/**
 * The flat list of Python types a JSON Schema accepts on the request side
 * ('None' for null). Registers the TypedDicts it needs.
 */
function pyMembers(node: unknown, imports: Set<string>): string[] {
  const s = (node ?? {}) as Json
  const ref = refName(s)
  if (ref) {
    const target = schemas[ref]
    if (isObjectSchema(target)) {
      paramTypedDicts.add(ref)
      return acceptModels ? [`${ref}Param`, ref] : [`${ref}Param`]
    }
    return pyMembers(target, imports)
  }
  const union = (s.anyOf ?? s.oneOf) as Json[] | undefined
  if (union) {
    let members = [...new Set(union.flatMap((m) => pyMembers(m, imports)))]
    // `str | Literal[""]` is just `str`.
    if (members.includes('str')) members = members.filter((m) => !/^Literal\["/.test(m))
    return members
  }
  if (s.const !== undefined) {
    imports.add('Literal')
    return [`Literal[${literal(s.const)}]`]
  }
  if (Array.isArray(s.enum)) {
    imports.add('Literal')
    return [`Literal[${(s.enum as unknown[]).map(literal).join(', ')}]`]
  }
  switch (s.type) {
    case 'null':
      return ['None']
    case 'string':
      if (s.format === 'date' || s.format === 'date-time') {
        imports.add('datetime')
        return ['str', `datetime.${s.format === 'date' ? 'date' : 'datetime'}`]
      }
      return ['str']
    case 'integer':
      return ['int']
    case 'number':
      return ['float']
    case 'boolean':
      return ['bool']
    case 'array':
      imports.add('Sequence')
      return [`Sequence[${pyType(s.items, imports)}]`]
    case 'object':
      if (isObjectSchema(s)) throw new Error('sdk-gen: inline object in a request param should have been hoisted')
      imports.add('Dict')
      return ['Dict[str, object]']
    default:
      return ['object']
  }
}

/** One annotation from a member list, e.g. `Union[str, datetime.date]` or `Optional[str]`. */
function annotate(members: string[], imports: Set<string>): string {
  const nonNull = members.filter((m) => m !== 'None')
  const nullable = nonNull.length !== members.length
  if (nonNull.length === 0) return 'None'
  if (nonNull.length > 1) imports.add('Union')
  const t = nonNull.length === 1 ? nonNull[0]! : `Union[${nonNull.join(', ')}]`
  if (!nullable) return t
  imports.add('Optional')
  return `Optional[${t}]`
}

function pyType(node: unknown, imports: Set<string>): string {
  return annotate(pyMembers(node, imports), imports)
}

/** The annotation of an optional keyword argument: its types plus NotGiven. */
function optionalKwargType(node: unknown, imports: Set<string>): string {
  imports.add('Union')
  const members = pyMembers(node, imports)
  const nonNull = members.filter((m) => m !== 'None')
  return `Union[${[...nonNull, 'NotGiven', ...(nonNull.length !== members.length ? ['None'] : [])].join(', ')}]`
}

/** The typing names a block of generated code actually uses. */
function usedTyping(code: string, candidates: string[]): string[] {
  return candidates.filter((n) => new RegExp(`\\b${n}\\[`).test(code)).sort()
}

function oneLine(text: unknown): string {
  return String(text ?? '')
    .replace(/\s+/g, ' ')
    .trim()
}

function docEscape(text: string): string {
  return text.replace(/\\/g, '\\\\').replace(/"""/g, '\\"\\"\\"')
}

function emitParams(): string {
  const imports = new Set<string>(['TypedDict'])
  const blocks: string[] = []
  const done = new Set<string>()
  // Registering a TypedDict can register more (nested refs), so loop until stable.
  for (;;) {
    const todo = [...paramTypedDicts].filter((n) => !done.has(n)).sort()
    if (!todo.length) break
    for (const name of todo) {
      done.add(name)
      const schema = schemas[name]!
      const required = new Set((schema.required as string[] | undefined) ?? [])
      const lines = [`class ${name}Param(TypedDict, total=False):`]
      const desc = oneLine(schema.description)
      lines.push(`    """${docEscape(desc || `The \`${name}\` object, as a request parameter.`)}"""`, '')
      for (const [prop, ps] of Object.entries(schema.properties as Record<string, Json>)) {
        if (PY_KEYWORDS.has(prop) || !/^[A-Za-z_][A-Za-z0-9_]*$/.test(prop)) {
          throw new Error(`sdk-gen: ${name}.${prop} is not a valid TypedDict key in Python`)
        }
        let t = pyType(ps, imports)
        if (required.has(prop)) {
          imports.add('Required')
          t = `Required[${t}]`
        }
        const d = oneLine(ps.description ?? deref(raw, ps).description)
        if (d) lines.push(`    ${prop}: ${t}`, `    """${docEscape(d)}"""`, '')
        else lines.push(`    ${prop}: ${t}`, '')
      }
      blocks.push(lines.join('\n').trimEnd())
    }
  }
  const names = [...done].sort().map((n) => `${n}Param`)
  const code = blocks.join('\n')
  const typing = usedTyping(code, ['Dict', 'Optional', 'Sequence', 'Union'])
  const ext = [...usedTyping(code, ['Literal', 'Required']), 'TypedDict'].sort()
  if (!/\bdatetime\./.test(code)) imports.delete('datetime')
  return [
    HEADER,
    '"""TypedDicts for nested request objects: pass plain dicts shaped like these (or the matching models)."""',
    '',
    'from __future__ import annotations',
    '',
    ...(imports.has('datetime') ? ['import datetime'] : []),
    ...(typing.length ? [`from typing import ${typing.join(', ')}`] : []),
    ...(imports.has('datetime') || typing.length ? [''] : []),
    `from typing_extensions import ${ext.join(', ')}`,
    '',
    `__all__ = [${names.map((n) => JSON.stringify(n)).join(', ')}]`,
    '',
    '',
    blocks.join('\n\n\n'),
    '',
  ].join('\n')
}

// ---------------------------------------------------------------------------
// 4. Resources.
// ---------------------------------------------------------------------------

interface Kwarg {
  name: string
  wire: string
  type: string
  /** Annotation when optional: the types plus NotGiven. */
  optType: string
  required: boolean
  description: string
  in: 'query' | 'body'
}

function kwargsFor(op: SpecOperation, imports: Set<string>): Kwarg[] {
  acceptModels = true
  try {
    return kwargsForInner(op, imports)
  } finally {
    acceptModels = false
  }
}

function kwargsForInner(op: SpecOperation, imports: Set<string>): Kwarg[] {
  const out: Kwarg[] = []
  for (const p of op.queryParams) {
    const ps = deref(raw, p.schema)
    out.push({
      name: pyIdent(p.name),
      wire: p.name,
      type: pyType(p.schema, imports),
      optType: optionalKwargType(p.schema, imports),
      required: p.required,
      description: oneLine(ps.description),
      in: 'query',
    })
  }
  if (op.hasBody) {
    const bodySchema = deref(raw, op.bodySchema)
    const name = refName(op.bodySchema)
    const hoisted = name ? schemas[name]! : bodySchema
    const required = new Set((hoisted.required as string[] | undefined) ?? [])
    for (const [prop, ps] of Object.entries((hoisted.properties ?? {}) as Record<string, Json>)) {
      out.push({
        name: pyIdent(prop),
        wire: prop,
        type: pyType(ps, imports),
        optType: optionalKwargType(ps, imports),
        required: required.has(prop),
        description: oneLine(ps.description ?? deref(raw, ps).description),
        in: 'body',
      })
    }
  }
  const seen = new Set<string>()
  for (const k of out) {
    if (RESERVED.has(k.name) || op.pathParams.includes(k.name) || seen.has(k.name)) {
      throw new Error(`sdk-gen: ${op.operationId} param "${k.name}" collides with another argument; rename it in python.ts`)
    }
    seen.add(k.name)
  }
  return [...out.filter((k) => k.required), ...out.filter((k) => !k.required)]
}

function docstring(op: SpecOperation, kwargs: Kwarg[], indent: string): string {
  const firstPara = oneLine(op.description.split(/\n\s*\n/)[0])
  const summary = op.summary ? `${op.summary}.`.replace(/\.\.$/, '.') : op.operationId
  const lines = [summary]
  if (firstPara && firstPara !== op.summary) lines.push('', firstPara)
  lines.push(
    '',
    `\`${op.method} ${op.path}\`${op.scope ? ` · scope \`${op.scope}\`` : ''}${op.method === 'POST' ? ' · idempotent (automatic key)' : ''}`,
  )
  const documented = kwargs.filter((k) => k.description)
  if (documented.length) {
    lines.push('', 'Args:')
    for (const k of documented) lines.push(`  ${k.name}: ${k.description}`)
  }
  const body = lines.map((l) => (l ? `${indent}${docEscape(l)}` : '')).join('\n')
  return `${indent}"""\n${body}\n${indent}"""`
}

const OPTION_ARGS = [
  'idempotency_key: Optional[str] = None',
  'timeout: Optional[float] = None',
  'max_retries: Optional[int] = None',
  'extra_headers: Optional[Mapping[str, str]] = None',
]

function pathExpr(op: SpecOperation): string {
  const parts = op.path.replace(/\{([^}]+)\}/g, (_m, name: string) => `{path_param('${name}', ${pyIdent(name)})}`)
  return op.pathParams.length ? `f"${parts}"` : `"${parts}"`
}

function dictExpr(kwargs: Kwarg[]): string {
  return `{${kwargs.map((k) => `"${k.wire}": ${k.name}`).join(', ')}}`
}

interface EmittedMethod {
  sync: string
  async: string
  name: string
  models: Set<string>
}

function emitOperation(op: SpecOperation, typingImports: Set<string>): EmittedMethod {
  const models = new Set<string>()
  const kwargs = kwargsFor(op, typingImports)
  const name = pyMethod(op)
  const model = returnModel.get(op.operationId)
  if (model) models.add(model)

  const sig = ['self', ...op.pathParams.map((p) => `${pyIdent(p)}: str`)]
  sig.push('*')
  for (const k of kwargs) {
    sig.push(k.required ? `${k.name}: ${k.type}` : `${k.name}: ${k.optType} = NOT_GIVEN`)
  }
  sig.push(...OPTION_ARGS)
  typingImports.add('Optional')
  typingImports.add('Mapping')

  const query = kwargs.filter((k) => k.in === 'query')
  const body = kwargs.filter((k) => k.in === 'body')
  const fields = [`method="${op.method}"`, `path=${pathExpr(op)}`]
  if (query.length) fields.push(`query=strip_not_given(${dictExpr(query)})`)
  if (op.hasBody) {
    fields.push(`body=strip_not_given(${dictExpr(body)})${op.bodyRequired ? '' : ' or None'}`)
  }
  fields.push('idempotency_key=idempotency_key', 'timeout=timeout', 'max_retries=max_retries', 'extra_headers=extra_headers')
  if (op.accept) fields.push(`accept="${op.accept}"`)
  if (op.scope) fields.push(`required_scope="${op.scope}"`)
  const specExpr = `RequestSpec(\n                ${fields.join(',\n                ')},\n            )`

  let syncRet: string
  let asyncRet: string
  let call: string
  let asyncCall: string
  switch (op.kind) {
    case 'page':
      syncRet = `SyncPage[${model}]`
      asyncRet = `AsyncPagePromise[${model}]`
      call = `self._client._request_page(\n            ${specExpr},\n            ${model},\n        )`
      asyncCall = call
      break
    case 'data':
    case 'body':
      syncRet = asyncRet = model!
      call = `self._client._request(\n            ${specExpr},\n            ${model},\n            "${op.kind}",\n        )`
      asyncCall = `await ${call}`
      break
    case 'binary':
      syncRet = asyncRet = 'bytes'
      call = `self._client._request_bytes(\n            ${specExpr},\n        )`
      asyncCall = `await ${call}`
      break
    case 'void':
      syncRet = asyncRet = 'None'
      call = `self._client._request_none(\n            ${specExpr},\n        )`
      asyncCall = `await ${call}`
      break
  }

  const doc = docstring(op, kwargs, '        ')
  const signature = sig.map((a) => `        ${a},`).join('\n')
  const syncStmt = op.kind === 'void' ? call : `return ${call}`
  const asyncStmt = op.kind === 'void' ? asyncCall : `return ${asyncCall}`
  let sync = `    def ${name}(\n${signature}\n    ) -> ${syncRet}:\n${doc}\n        ${syncStmt}`
  const asyncDef = op.kind === 'page' ? 'def' : 'async def'
  let asyncM = `    ${asyncDef} ${name}(\n${signature}\n    ) -> ${asyncRet}:\n${doc}\n        ${asyncStmt}`

  // Binary downloads also get a URL helper (fetching it still needs the API key).
  if (op.kind === 'binary' && op.method === 'GET') {
    const urlSig = ['self', ...op.pathParams.map((p) => `${pyIdent(p)}: str`)]
    if (query.length) {
      urlSig.push('*', ...query.map((k) => (k.required ? `${k.name}: ${k.type}` : `${k.name}: ${k.optType} = NOT_GIVEN`)))
    }
    const queryArg = query.length ? `, strip_not_given(${dictExpr(query)})` : ''
    const helper =
      `\n\n    def ${name}_url(${urlSig.join(', ')}) -> str:\n` +
      `        """The absolute URL of \`${op.method} ${op.path}\`. Fetching it still needs \`Authorization: Bearer <key>\`."""\n` +
      `        return build_url(self._client.base_url, ${pathExpr(op)}${queryArg})`
    sync += helper
    asyncM += helper
  }
  return { sync, async: asyncM, name, models }
}

function className(r: SpecResource): string {
  return spec.schemaNames.includes(r.plural) ? `${r.plural}Resource` : r.plural
}

function emitResource(resource: SpecResource, ops: SpecOperation[]): string {
  const typingImports = new Set<string>()
  const emitted = ops.map((op) => emitOperation(op, typingImports))
  const params = [...new Set(emitted.flatMap((e) => [...e.sync.matchAll(/\b(\w+Param)\b/g)].map((m) => m[1]!)))].sort()
  const models = [...new Set([...emitted.flatMap((e) => [...e.models]), ...params.map((p) => p.replace(/Param$/, ''))])].sort()
  const cls = className(resource)
  const usesPage = ops.some((o) => o.kind === 'page')
  const usesUrl = ops.some((o) => o.kind === 'binary' && o.method === 'GET')
  const usesPath = ops.some((o) => o.pathParams.length)
  const usesStrip = emitted.some((e) => e.sync.includes('strip_not_given('))
  const usesNotGiven = emitted.some((e) => e.sync.includes('NOT_GIVEN'))
  const code = emitted.map((e) => e.sync + e.async).join('\n')
  const typing = usedTyping(code, ['Dict', 'Mapping', 'Optional', 'Sequence', 'Union'])
  const ext = usedTyping(code, ['Literal'])

  const utils = [...(usesPath ? ['path_param'] : []), ...(usesStrip ? ['strip_not_given'] : [])]
  const lines = [
    HEADER,
    `"""${resource.tag}: \`client.${resource.snake}\`."""`,
    '',
    'from __future__ import annotations',
    '',
    ...(/\bdatetime\./.test(code) ? ['import datetime'] : []),
    `from functools import cached_property`,
    `from typing import ${typing.join(', ')}`,
    '',
    ...(ext.length ? [`from typing_extensions import ${ext.join(', ')}`, ''] : []),
    `from .._resource import AsyncAPIResource, SyncAPIResource`,
    `from .._response import async_to_raw_response_wrapper, to_raw_response_wrapper`,
    ...(usesUrl ? [`from .._retry import build_url`] : []),
    `from .._types import ${[...(usesNotGiven ? ['NOT_GIVEN', 'NotGiven'] : []), 'RequestSpec'].join(', ')}`,
    ...(utils.length ? [`from .._utils import ${utils.join(', ')}`] : []),
    ...(usesPage ? [`from ..pagination import AsyncPagePromise, SyncPage`] : []),
    ...(models.length ? [`from ..types import ${models.join(', ')}`] : []),
    ...(params.length ? [`from ..types.params import ${params.join(', ')}`] : []),
    '',
    `__all__ = ["Async${cls}", "${cls}"]`,
    '',
    '',
    `class ${cls}(SyncAPIResource):`,
    `    """${resource.tag}: \`client.${resource.snake}\`."""`,
    '',
    '    @cached_property',
    `    def with_raw_response(self) -> ${cls}WithRawResponse:`,
    '        """The same methods, returning the raw response: `.with_raw_response.<method>(...)` → `.parse()`, `.headers`, `.request_id`."""',
    `        return ${cls}WithRawResponse(self)`,
    '',
    emitted.map((e) => e.sync).join('\n\n'),
    '',
    '',
    `class Async${cls}(AsyncAPIResource):`,
    `    """${resource.tag}: \`client.${resource.snake}\` (async)."""`,
    '',
    '    @cached_property',
    `    def with_raw_response(self) -> Async${cls}WithRawResponse:`,
    '        """The same methods, returning the raw response: `await .with_raw_response.<method>(...)` → `.parse()`, `.headers`."""',
    `        return Async${cls}WithRawResponse(self)`,
    '',
    emitted.map((e) => e.async).join('\n\n'),
    '',
    '',
    `class ${cls}WithRawResponse:`,
    `    def __init__(self, resource: ${cls}) -> None:`,
    ...emitted.map((e) => `        self.${e.name} = to_raw_response_wrapper(resource.${e.name})`),
    '',
    '',
    `class Async${cls}WithRawResponse:`,
    `    def __init__(self, resource: Async${cls}) -> None:`,
    ...emitted.map((e) => `        self.${e.name} = async_to_raw_response_wrapper(resource.${e.name})`),
    '',
  ]
  return lines.join('\n').replace(/\n{4,}/g, '\n\n\n')
}

// ---------------------------------------------------------------------------
// 5. Write everything.
// ---------------------------------------------------------------------------

function write(path: string, content: string) {
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, content)
  console.log(`  wrote ${path.slice(ROOT.length + 1)}`)
}

const resourcesDir = join(SRC, 'resources')
mkdirSync(resourcesDir, { recursive: true })
for (const f of readdirSync(resourcesDir)) {
  if (f.endsWith('.py')) rmSync(join(resourcesDir, f))
}

const resourceModules: { resource: SpecResource; module: string; cls: string }[] = []
for (const resource of spec.resources) {
  const ops = spec.operations.filter((o) => o.resource === resource)
  write(join(resourcesDir, `${resource.snake}.py`), emitResource(resource, ops))
  resourceModules.push({ resource, module: resource.snake, cls: className(resource) })
}

write(
  join(resourcesDir, '__init__.py'),
  [
    HEADER,
    '"""One class per API tag, plus the client bases that carry them."""',
    '',
    'from __future__ import annotations',
    '',
    'from functools import cached_property',
    '',
    'from .._base_client import AsyncAPIClient, SyncAPIClient',
    ...[...resourceModules].sort((a, b) => a.module.localeCompare(b.module)).map((m) => `from .${m.module} import Async${m.cls}, ${m.cls}`),
    '',
    `__all__ = [`,
    ...[...resourceModules.flatMap((m) => [`Async${m.cls}`, m.cls]), 'AsyncInvoiceAIResources', 'InvoiceAIResources']
      .sort()
      .map((n) => `    "${n}",`),
    ']',
    '',
    '',
    'class InvoiceAIResources(SyncAPIClient):',
    '    """The client with every API resource attached. `InvoiceAI` extends this."""',
    ...resourceModules.flatMap((m) => [
      '',
      '    @cached_property',
      `    def ${m.module}(self) -> ${m.cls}:`,
      `        """${m.resource.tag}."""`,
      `        return ${m.cls}(self)`,
    ]),
    '',
    '',
    'class AsyncInvoiceAIResources(AsyncAPIClient):',
    '    """The async client with every API resource attached. `AsyncInvoiceAI` extends this."""',
    ...resourceModules.flatMap((m) => [
      '',
      '    @cached_property',
      `    def ${m.module}(self) -> Async${m.cls}:`,
      `        """${m.resource.tag}."""`,
      `        return Async${m.cls}(self)`,
    ]),
    '',
  ].join('\n'),
)

write(join(SRC, 'types', 'params.py'), emitParams())

generateModels()

// types/__init__.py re-exports every model class datamodel-codegen produced.
const generatedPath = join(SRC, 'types', '_generated.py')
const modelNames = existsSync(generatedPath)
  ? [...readFileSync(generatedPath, 'utf8').matchAll(/^class ([A-Za-z]\w*)\(/gm)].map((m) => m[1]!)
  : []
for (const needed of new Set(returnModel.values())) {
  if (existsSync(generatedPath) && !modelNames.includes(needed)) {
    throw new Error(`sdk-gen: model ${needed} is missing from types/_generated.py`)
  }
}
const paramNames = [...readFileSync(join(SRC, 'types', 'params.py'), 'utf8').matchAll(/^class ([A-Za-z]\w*)\(/gm)].map(
  (m) => m[1]!,
)
write(
  join(SRC, 'types', '__init__.py'),
  [
    HEADER,
    '"""Models for every API object (Pydantic v2) and TypedDicts for nested request params."""',
    '',
    'from __future__ import annotations',
    '',
    `from ._generated import (`,
    ...[...modelNames].sort().map((n) => `    ${n},`),
    ')',
    `from .params import (`,
    ...[...paramNames].sort().map((n) => `    ${n},`),
    ')',
    '',
    '__all__ = [',
    ...[...modelNames, ...paramNames].sort().map((n) => `    "${n}",`),
    ']',
    '',
  ].join('\n'),
)

write(
  join(SRC, '_meta.py'),
  [HEADER, '#: OpenAPI `info.version` of the spec this SDK was generated from, sent as `Invoice-AI-Version`.', `API_VERSION = "${spec.version}"`, ''].join('\n'),
)

write(
  join(SRC, '_operations.py'),
  [
    HEADER,
    '"""Every API operation and the SDK method that calls it."""',
    '',
    'from __future__ import annotations',
    '',
    'from typing import Optional, Tuple',
    '',
    'from typing_extensions import TypedDict',
    '',
    '',
    'class Operation(TypedDict):',
    '    operation_id: str',
    '    http_method: str',
    '    path: str',
    '    resource: str',
    '    method: str',
    '    kind: str',
    '    scope: Optional[str]',
    '',
    '',
    'OPERATIONS: Tuple[Operation, ...] = (',
    ...spec.operations.map(
      (o) =>
        `    {"operation_id": "${o.operationId}", "http_method": "${o.method}", "path": "${o.path}", "resource": "${o.resource.snake}", "method": "${pyMethod(o)}", "kind": "${o.kind}", "scope": ${o.scope ? `"${o.scope}"` : 'None'}},`,
    ),
    ')',
    '',
  ].join('\n'),
)

console.log(`sdk-gen (python): ${spec.operations.length} operations across ${spec.resources.length} resources (spec ${spec.version}).`)
