/**
 * Generates the TypeScript SDK's resource classes from api-docs/openapi.json.
 *
 *   pnpm sdk:gen        (regenerates schema.d.ts first, then runs this)
 *
 * Writes, under packages/sdk-ts/src:
 *   generated/types.ts       one alias per component schema (Customer, Invoice…)
 *   generated/operations.ts  operationId → resource.method manifest (tests use it)
 *   generated/meta.ts        API version from info.version
 *   resources/<name>.ts      one class per tag
 *   resources/index.ts       InvoiceAIResources: the client with every resource attached
 *
 * Never edit those files by hand; change the spec or this script and rerun.
 */
import { mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { loadSpec, type SpecOperation, type SpecResource } from './spec'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const SPEC = join(ROOT, 'api-docs', 'openapi.json')
const SRC = join(ROOT, 'packages', 'sdk-ts', 'src')
const HEADER = '// Generated by scripts/sdk-gen/ts.ts from api-docs/openapi.json. Do not edit.\n'

const spec = loadSpec(SPEC)
const schemaNames = new Set(spec.schemaNames)

const pascal = (s: string) => s.charAt(0).toUpperCase() + s.slice(1)
const kebab = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()

function className(r: SpecResource): string {
  return schemaNames.has(r.plural) ? `${r.plural}Resource` : r.plural
}

/** `del` reads badly in type names: InvoiceItemDeleteParams. */
function typeStem(op: SpecOperation): string {
  return op.resource.singular + pascal(op.sdkMethod === 'del' ? 'delete' : op.sdkMethod)
}

function jsdoc(op: SpecOperation, indent: string): string {
  const firstPara = op.description.split(/\n\s*\n/)[0]?.replace(/\s+/g, ' ').trim() ?? ''
  const lines = [
    op.summary ? `${op.summary}.`.replace(/\.\.$/, '.') : '',
    firstPara && firstPara !== op.summary ? firstPara : '',
    `\`${op.method} ${op.path}\`${op.scope ? ` · scope \`${op.scope}\`` : ''}${op.method === 'POST' ? ' · idempotent (automatic key)' : ''}`,
  ].filter(Boolean)
  const safe = lines.map((l) => l.replace(/\*\//g, '*\\/'))
  return [`${indent}/**`, ...safe.map((l) => `${indent} * ${l}`), `${indent} */`].join('\n')
}

interface Emitted {
  typeDecls: string[]
  method: string
  imports: Set<string>
  paramTypeNames: string[]
}

function opRef(op: SpecOperation): string {
  return `operations['${op.operationId}']`
}

function emitOperation(op: SpecOperation): Emitted {
  const imports = new Set<string>()
  const typeDecls: string[] = []
  const paramTypeNames: string[] = []
  const stem = typeStem(op)
  const ref = opRef(op)

  // --- params type: query params and/or JSON body, merged into one object.
  const parts: string[] = []
  if (op.queryParams.length) parts.push(`NonNullable<${ref}['parameters']['query']>`)
  if (op.hasBody) parts.push(`NonNullable<${ref}['requestBody']>['content']['application/json']`)
  const hasParams = parts.length > 0
  const paramsRequired = op.bodyRequired || op.queryParams.some((p) => p.required)
  const paramsType = `${stem}Params`
  if (hasParams) {
    typeDecls.push(`export type ${paramsType} = ${parts.join(' & ')}`)
    paramTypeNames.push(paramsType)
  }

  // --- return type
  const successJson = `${ref}['responses'][${op.successStatus}]['content']['application/json']`
  let returnType: string
  let call: string
  const dataType = (suffix: string) => {
    if (op.dataRef && schemaNames.has(op.dataRef)) {
      imports.add(op.dataRef)
      return op.dataRef
    }
    // Inline schema: give it a readable name instead of a long indexed type.
    const name = `${stem}${suffix ? 'Item' : 'Result'}`
    typeDecls.push(`export type ${name} = ${successJson}['data']${suffix}`)
    paramTypeNames.push(name)
    return name
  }
  switch (op.kind) {
    case 'page':
      returnType = `PagePromise<${dataType('[number]')}>`
      call = '_requestPage'
      break
    case 'data':
      returnType = `APIPromise<${dataType('')}>`
      call = '_request'
      break
    case 'body': {
      const name = `${stem}Response`
      typeDecls.push(`export type ${name} = ${successJson}`)
      paramTypeNames.push(name)
      returnType = `APIPromise<${name}>`
      call = '_request'
      break
    }
    case 'binary':
      returnType = 'APIPromise<ArrayBuffer>'
      call = '_request'
      break
    case 'void':
      returnType = 'APIPromise<void>'
      call = '_request'
      break
  }

  // --- signature: path params, then params, then request options.
  const args = op.pathParams.map((p) => `${p}: string`)
  if (hasParams) args.push(`params${paramsRequired ? '' : '?'}: ${paramsType}`)
  args.push('options?: RequestOptions')

  const pathExpr =
    '`' + op.path.replace(/\{([^}]+)\}/g, (_m, name: string) => `\${pathParam('${name}', ${name})}`) + '`'

  const queryKeys = op.queryParams.map((p) => `'${p.name}'`).join(', ')
  const body: string[] = []
  let queryExpr = 'undefined'
  let bodyExpr = 'undefined'
  if (op.queryParams.length && op.hasBody) {
    body.push(`    const { query, body } = splitParams(params, [${queryKeys}])`)
    queryExpr = 'query'
    bodyExpr = 'body'
  } else if (op.queryParams.length) {
    queryExpr = 'params'
  } else if (op.hasBody) {
    bodyExpr = 'params'
  }
  const specFields = [
    `method: '${op.method}'`,
    `path: ${pathExpr}`,
    ...(queryExpr !== 'undefined' ? [`query: ${queryExpr}`] : []),
    ...(bodyExpr !== 'undefined' ? [`body: ${bodyExpr}`] : []),
    'options',
    ...(op.accept ? [`accept: '${op.accept}'`] : []),
    ...(op.scope ? [`requiredScope: '${op.scope}'`] : []),
  ]
  const shape = op.kind === 'page' ? '' : `, '${op.kind}'`
  const typeArg = returnType.replace(/^(PagePromise|APIPromise)<(.*)>$/, '$2')
  body.push(`    return this._client.${call}<${typeArg}>({ ${specFields.join(', ')} }${shape})`)

  let method = `${jsdoc(op, '  ')}\n  ${op.sdkMethod}(${args.join(', ')}): ${returnType} {\n${body.join('\n')}\n  }`

  // Binary downloads also get a URL helper (the URL needs the API key to fetch).
  if (op.kind === 'binary' && op.method === 'GET') {
    const urlArgs = op.pathParams.map((p) => `${p}: string`)
    if (hasParams) urlArgs.push(`params?: ${paramsType}`)
    method +=
      `\n\n  /** The absolute URL of \`${op.method} ${op.path}\`. Fetching it still needs \`Authorization: Bearer <key>\`. */\n` +
      `  ${op.sdkMethod}Url(${urlArgs.join(', ')}): string {\n` +
      `    return buildURL(this._client.baseURL, ${pathExpr}${hasParams ? ', params' : ''})\n  }`
  }

  return { typeDecls, method, imports, paramTypeNames }
}

function emitResource(resource: SpecResource, ops: SpecOperation[]): { file: string; exports: string[] } {
  const emitted = ops.map(emitOperation)
  const schemaImports = [...new Set(emitted.flatMap((e) => [...e.imports]))].sort()
  const usesSplit = ops.some((o) => o.queryParams.length && o.hasBody)
  const usesPath = ops.some((o) => o.pathParams.length)
  const usesPage = ops.some((o) => o.kind === 'page')
  const usesPromise = ops.some((o) => o.kind !== 'page')
  const usesUrl = ops.some((o) => o.kind === 'binary' && o.method === 'GET')
  const coreImports = ['APIResource', ...(usesPath ? ['pathParam'] : []), ...(usesSplit ? ['splitParams'] : [])]
  const cls = className(resource)

  const lines = [
    HEADER,
    ...(usesPromise ? [`import type { APIPromise } from '../core/api-promise'`] : []),
    `import { ${coreImports.join(', ')} } from '../core/client'`,
    `import ${usesUrl ? '{ buildURL, type RequestOptions }' : 'type { RequestOptions }'} from '../core/http'`,
    ...(usesPage ? [`import type { PagePromise } from '../core/pagination'`] : []),
    ...(emitted.some((e) => [e.method, ...e.typeDecls].some((s) => s.includes('operations[')))
      ? [`import type { operations } from '../generated/schema'`]
      : []),
    ...(schemaImports.length ? [`import type { ${schemaImports.join(', ')} } from '../generated/types'`] : []),
    '',
    ...emitted.flatMap((e) => e.typeDecls),
    '',
    `/** ${resource.tag}: \`invoiceai.${resource.property}\`. */`,
    `export class ${cls} extends APIResource {`,
    emitted.map((e) => e.method).join('\n\n'),
    '}',
    '',
  ]
  return { file: lines.join('\n').replace(/\n{3,}/g, '\n\n'), exports: [cls, ...emitted.flatMap((e) => e.paramTypeNames)] }
}

function write(path: string, content: string) {
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, content)
  console.log(`  wrote ${path.slice(ROOT.length + 1)}`)
}

// --- generated/types.ts
write(
  join(SRC, 'generated', 'types.ts'),
  [
    HEADER,
    `import type { components } from './schema'`,
    '',
    ...spec.schemaNames.map((n) => `export type ${n} = components['schemas']['${n}']`),
    '',
  ].join('\n'),
)

// --- generated/meta.ts
write(
  join(SRC, 'generated', 'meta.ts'),
  [HEADER, `/** OpenAPI \`info.version\` of the spec this SDK was generated from. */`, `export const API_VERSION = '${spec.version}'`, ''].join('\n'),
)

// --- generated/operations.ts
write(
  join(SRC, 'generated', 'operations.ts'),
  [
    HEADER,
    '/** Every API operation and the SDK method that calls it. */',
    'export const OPERATIONS = [',
    ...spec.operations.map(
      (o) =>
        `  { operationId: '${o.operationId}', httpMethod: '${o.method}', path: '${o.path}', resource: '${o.resource.property}', method: '${o.sdkMethod}', kind: '${o.kind}', scope: ${o.scope ? `'${o.scope}'` : 'undefined'} },`,
    ),
    '] as const',
    '',
    'export type OperationId = (typeof OPERATIONS)[number][\'operationId\']',
    '',
  ].join('\n'),
)

// --- resources/*.ts
const resourcesDir = join(SRC, 'resources')
mkdirSync(resourcesDir, { recursive: true })
for (const f of readdirSync(resourcesDir)) rmSync(join(resourcesDir, f))

const indexExports: string[] = []
for (const resource of spec.resources) {
  const ops = spec.operations.filter((o) => o.resource === resource)
  const fileBase = kebab(resource.property)
  const { file, exports } = emitResource(resource, ops)
  write(join(resourcesDir, `${fileBase}.ts`), file)
  const [cls, ...types] = exports
  indexExports.push(`export { ${cls} } from './${fileBase}'`)
  if (types.length) indexExports.push(`export type { ${types.join(', ')} } from './${fileBase}'`)
}

write(
  join(resourcesDir, 'index.ts'),
  [
    HEADER,
    `import { BaseClient } from '../core/client'`,
    ...spec.resources.map((r) => `import { ${className(r)} } from './${kebab(r.property)}'`),
    '',
    ...indexExports,
    '',
    '/** The client with every API resource attached. `InvoiceAI` extends this. */',
    'export class InvoiceAIResources extends BaseClient {',
    ...spec.resources.map((r) => `  /** ${r.tag}. */\n  readonly ${r.property}: ${className(r)} = new ${className(r)}(this)`),
    '}',
    '',
  ].join('\n'),
)

console.log(`sdk-gen: ${spec.operations.length} operations across ${spec.resources.length} resources (spec ${spec.version}).`)
