# Generated by scripts/sdk-gen/python.ts from api-docs/openapi.json. Do not edit.

"""One class per API tag, plus the client bases that carry them."""

from __future__ import annotations

from functools import cached_property

from .._base_client import AsyncAPIClient, SyncAPIClient
from .business import AsyncBusinessResource, BusinessResource
from .customers import AsyncCustomers, Customers
from .invoice_items import AsyncInvoiceItems, InvoiceItems
from .invoices import AsyncInvoices, Invoices
from .prices import AsyncPrices, Prices
from .products import AsyncProducts, Products
from .webhook_endpoints import AsyncWebhookEndpoints, WebhookEndpoints

__all__ = [
    "AsyncBusinessResource",
    "AsyncCustomers",
    "AsyncInvoiceAIResources",
    "AsyncInvoiceItems",
    "AsyncInvoices",
    "AsyncPrices",
    "AsyncProducts",
    "AsyncWebhookEndpoints",
    "BusinessResource",
    "Customers",
    "InvoiceAIResources",
    "InvoiceItems",
    "Invoices",
    "Prices",
    "Products",
    "WebhookEndpoints",
]


class InvoiceAIResources(SyncAPIClient):
    """The client with every API resource attached. `InvoiceAI` extends this."""

    @cached_property
    def business(self) -> BusinessResource:
        """Business."""
        return BusinessResource(self)

    @cached_property
    def customers(self) -> Customers:
        """Customers."""
        return Customers(self)

    @cached_property
    def products(self) -> Products:
        """Products."""
        return Products(self)

    @cached_property
    def prices(self) -> Prices:
        """Prices."""
        return Prices(self)

    @cached_property
    def invoices(self) -> Invoices:
        """Invoices."""
        return Invoices(self)

    @cached_property
    def invoice_items(self) -> InvoiceItems:
        """Invoice items."""
        return InvoiceItems(self)

    @cached_property
    def webhook_endpoints(self) -> WebhookEndpoints:
        """Webhook endpoints."""
        return WebhookEndpoints(self)


class AsyncInvoiceAIResources(AsyncAPIClient):
    """The async client with every API resource attached. `AsyncInvoiceAI` extends this."""

    @cached_property
    def business(self) -> AsyncBusinessResource:
        """Business."""
        return AsyncBusinessResource(self)

    @cached_property
    def customers(self) -> AsyncCustomers:
        """Customers."""
        return AsyncCustomers(self)

    @cached_property
    def products(self) -> AsyncProducts:
        """Products."""
        return AsyncProducts(self)

    @cached_property
    def prices(self) -> AsyncPrices:
        """Prices."""
        return AsyncPrices(self)

    @cached_property
    def invoices(self) -> AsyncInvoices:
        """Invoices."""
        return AsyncInvoices(self)

    @cached_property
    def invoice_items(self) -> AsyncInvoiceItems:
        """Invoice items."""
        return AsyncInvoiceItems(self)

    @cached_property
    def webhook_endpoints(self) -> AsyncWebhookEndpoints:
        """Webhook endpoints."""
        return AsyncWebhookEndpoints(self)
