# Generated by scripts/sdk-gen/python.ts from api-docs/openapi.json. Do not edit.

"""Business: `client.business`."""

from __future__ import annotations

from functools import cached_property
from typing import Mapping, Optional

from .._resource import AsyncAPIResource, SyncAPIResource
from .._response import async_to_raw_response_wrapper, to_raw_response_wrapper
from .._types import RequestSpec
from ..types import Business

__all__ = ["AsyncBusinessResource", "BusinessResource"]


class BusinessResource(SyncAPIResource):
    """Business: `client.business`."""

    @cached_property
    def with_raw_response(self) -> BusinessResourceWithRawResponse:
        """The same methods, returning the raw response: `.with_raw_response.<method>(...)` → `.parse()`, `.headers`, `.request_id`."""
        return BusinessResourceWithRawResponse(self)

    def retrieve(
        self,
        *,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Business:
        """
        Retrieve the business profile.

        Returns the business profile invoices are issued from: legal name, address, tax id, default currency, bank details and invoice prefix. Read-only — the profile is edited in the app.

        `GET /business` · scope `business:read`
        """
        return self._client._request(
            RequestSpec(
                method="GET",
                path="/business",
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="business:read",
            ),
            Business,
            "data",
        )


class AsyncBusinessResource(AsyncAPIResource):
    """Business: `client.business` (async)."""

    @cached_property
    def with_raw_response(self) -> AsyncBusinessResourceWithRawResponse:
        """The same methods, returning the raw response: `await .with_raw_response.<method>(...)` → `.parse()`, `.headers`."""
        return AsyncBusinessResourceWithRawResponse(self)

    async def retrieve(
        self,
        *,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Business:
        """
        Retrieve the business profile.

        Returns the business profile invoices are issued from: legal name, address, tax id, default currency, bank details and invoice prefix. Read-only — the profile is edited in the app.

        `GET /business` · scope `business:read`
        """
        return await self._client._request(
            RequestSpec(
                method="GET",
                path="/business",
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="business:read",
            ),
            Business,
            "data",
        )


class BusinessResourceWithRawResponse:
    def __init__(self, resource: BusinessResource) -> None:
        self.retrieve = to_raw_response_wrapper(resource.retrieve)


class AsyncBusinessResourceWithRawResponse:
    def __init__(self, resource: AsyncBusinessResource) -> None:
        self.retrieve = async_to_raw_response_wrapper(resource.retrieve)
