# Generated by scripts/sdk-gen/python.ts from api-docs/openapi.json. Do not edit.

"""Customers: `client.customers`."""

from __future__ import annotations

from functools import cached_property
from typing import Mapping, Optional, Union

from .._resource import AsyncAPIResource, SyncAPIResource
from .._response import async_to_raw_response_wrapper, to_raw_response_wrapper
from .._types import NOT_GIVEN, NotGiven, RequestSpec
from .._utils import path_param, strip_not_given
from ..pagination import AsyncPagePromise, SyncPage
from ..types import Customer, CustomerCreateAddress, CustomerUpdateAddress
from ..types.params import CustomerCreateAddressParam, CustomerUpdateAddressParam

__all__ = ["AsyncCustomers", "Customers"]


class Customers(SyncAPIResource):
    """Customers: `client.customers`."""

    @cached_property
    def with_raw_response(self) -> CustomersWithRawResponse:
        """The same methods, returning the raw response: `.with_raw_response.<method>(...)` → `.parse()`, `.headers`, `.request_id`."""
        return CustomersWithRawResponse(self)

    def list(
        self,
        *,
        cursor: Union[str, NotGiven] = NOT_GIVEN,
        limit: Union[int, NotGiven] = NOT_GIVEN,
        query: Union[str, NotGiven] = NOT_GIVEN,
        include_deleted: Union[bool, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> SyncPage[Customer]:
        """
        List customers.

        Returns customers newest first, cursor-paginated. Archived customers are excluded unless `include_deleted=true`.

        `GET /customers` · scope `clients:read`

        Args:
          cursor: The `next_cursor` from the previous page. Opaque — do not build it yourself.
          limit: Page size, 1–100. Defaults to 25.
          query: Case-insensitive substring match on `name`.
          include_deleted: Include archived customers. Only the literal `true` enables it.
        """
        return self._client._request_page(
            RequestSpec(
                method="GET",
                path="/customers",
                query=strip_not_given({"cursor": cursor, "limit": limit, "query": query, "include_deleted": include_deleted}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="clients:read",
            ),
            Customer,
        )

    def create(
        self,
        *,
        name: str,
        email: Union[str, NotGiven] = NOT_GIVEN,
        phone: Union[str, NotGiven] = NOT_GIVEN,
        tax_id: Union[str, NotGiven] = NOT_GIVEN,
        address: Union[CustomerCreateAddressParam, CustomerCreateAddress, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Customer:
        """
        Create a customer.

        Creates a customer you can bill. Only `name` is required. Creating does not deduplicate — two calls with the same name make two customers.

        `POST /customers` · scope `clients:write` · idempotent (automatic key)

        Args:
          name: Full name or legal business name.
          email: Billing email. `POST /invoices/{id}/send` delivers here unless you pass `to`. `""` clears it.
          phone: Phone number, free text.
          tax_id: Tax registration number (VAT, EIN, GSTIN…), free text — no format check.
          address: Billing address. Every field is optional.
        """
        return self._client._request(
            RequestSpec(
                method="POST",
                path="/customers",
                body=strip_not_given({"name": name, "email": email, "phone": phone, "tax_id": tax_id, "address": address}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="clients:write",
            ),
            Customer,
            "data",
        )

    def retrieve(
        self,
        id: str,
        *,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Customer:
        """
        Retrieve a customer.

        Returns one customer by `cus_…` id or UUID, including archived ones (`deleted: true`).

        `GET /customers/{id}` · scope `clients:read`
        """
        return self._client._request(
            RequestSpec(
                method="GET",
                path=f"/customers/{path_param('id', id)}",
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="clients:read",
            ),
            Customer,
            "data",
        )

    def update(
        self,
        id: str,
        *,
        name: Union[str, NotGiven] = NOT_GIVEN,
        email: Union[str, NotGiven] = NOT_GIVEN,
        phone: Union[str, NotGiven] = NOT_GIVEN,
        tax_id: Union[str, NotGiven] = NOT_GIVEN,
        address: Union[CustomerUpdateAddressParam, CustomerUpdateAddress, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Customer:
        """
        Update a customer.

        Updates the fields you send and leaves the rest unchanged. Existing invoices are not affected — each invoice keeps a snapshot of the customer as billed. Naturally idempotent, so no `Idempotency-Key` is needed.

        `PATCH /customers/{id}` · scope `clients:write`

        Args:
          name: Full name or legal business name.
          email: Billing email. `POST /invoices/{id}/send` delivers here unless you pass `to`. `""` clears it.
          phone: Phone number, free text.
          tax_id: Tax registration number (VAT, EIN, GSTIN…), free text — no format check.
          address: Billing address. Every field is optional.
        """
        return self._client._request(
            RequestSpec(
                method="PATCH",
                path=f"/customers/{path_param('id', id)}",
                body=strip_not_given({"name": name, "email": email, "phone": phone, "tax_id": tax_id, "address": address}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="clients:write",
            ),
            Customer,
            "data",
        )

    def delete(
        self,
        id: str,
        *,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Customer:
        """
        Archive a customer.

        Archives the customer (`deleted: true`) instead of deleting it: issued invoices reference customers and must keep naming who they were billed to. Archived customers drop out of `GET /customers` but stay readable by id. Archiving an archived customer succeeds and changes nothing.

        `DELETE /customers/{id}` · scope `clients:write`
        """
        return self._client._request(
            RequestSpec(
                method="DELETE",
                path=f"/customers/{path_param('id', id)}",
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="clients:write",
            ),
            Customer,
            "data",
        )


class AsyncCustomers(AsyncAPIResource):
    """Customers: `client.customers` (async)."""

    @cached_property
    def with_raw_response(self) -> AsyncCustomersWithRawResponse:
        """The same methods, returning the raw response: `await .with_raw_response.<method>(...)` → `.parse()`, `.headers`."""
        return AsyncCustomersWithRawResponse(self)

    def list(
        self,
        *,
        cursor: Union[str, NotGiven] = NOT_GIVEN,
        limit: Union[int, NotGiven] = NOT_GIVEN,
        query: Union[str, NotGiven] = NOT_GIVEN,
        include_deleted: Union[bool, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> AsyncPagePromise[Customer]:
        """
        List customers.

        Returns customers newest first, cursor-paginated. Archived customers are excluded unless `include_deleted=true`.

        `GET /customers` · scope `clients:read`

        Args:
          cursor: The `next_cursor` from the previous page. Opaque — do not build it yourself.
          limit: Page size, 1–100. Defaults to 25.
          query: Case-insensitive substring match on `name`.
          include_deleted: Include archived customers. Only the literal `true` enables it.
        """
        return self._client._request_page(
            RequestSpec(
                method="GET",
                path="/customers",
                query=strip_not_given({"cursor": cursor, "limit": limit, "query": query, "include_deleted": include_deleted}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="clients:read",
            ),
            Customer,
        )

    async def create(
        self,
        *,
        name: str,
        email: Union[str, NotGiven] = NOT_GIVEN,
        phone: Union[str, NotGiven] = NOT_GIVEN,
        tax_id: Union[str, NotGiven] = NOT_GIVEN,
        address: Union[CustomerCreateAddressParam, CustomerCreateAddress, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Customer:
        """
        Create a customer.

        Creates a customer you can bill. Only `name` is required. Creating does not deduplicate — two calls with the same name make two customers.

        `POST /customers` · scope `clients:write` · idempotent (automatic key)

        Args:
          name: Full name or legal business name.
          email: Billing email. `POST /invoices/{id}/send` delivers here unless you pass `to`. `""` clears it.
          phone: Phone number, free text.
          tax_id: Tax registration number (VAT, EIN, GSTIN…), free text — no format check.
          address: Billing address. Every field is optional.
        """
        return await self._client._request(
            RequestSpec(
                method="POST",
                path="/customers",
                body=strip_not_given({"name": name, "email": email, "phone": phone, "tax_id": tax_id, "address": address}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="clients:write",
            ),
            Customer,
            "data",
        )

    async def retrieve(
        self,
        id: str,
        *,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Customer:
        """
        Retrieve a customer.

        Returns one customer by `cus_…` id or UUID, including archived ones (`deleted: true`).

        `GET /customers/{id}` · scope `clients:read`
        """
        return await self._client._request(
            RequestSpec(
                method="GET",
                path=f"/customers/{path_param('id', id)}",
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="clients:read",
            ),
            Customer,
            "data",
        )

    async def update(
        self,
        id: str,
        *,
        name: Union[str, NotGiven] = NOT_GIVEN,
        email: Union[str, NotGiven] = NOT_GIVEN,
        phone: Union[str, NotGiven] = NOT_GIVEN,
        tax_id: Union[str, NotGiven] = NOT_GIVEN,
        address: Union[CustomerUpdateAddressParam, CustomerUpdateAddress, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Customer:
        """
        Update a customer.

        Updates the fields you send and leaves the rest unchanged. Existing invoices are not affected — each invoice keeps a snapshot of the customer as billed. Naturally idempotent, so no `Idempotency-Key` is needed.

        `PATCH /customers/{id}` · scope `clients:write`

        Args:
          name: Full name or legal business name.
          email: Billing email. `POST /invoices/{id}/send` delivers here unless you pass `to`. `""` clears it.
          phone: Phone number, free text.
          tax_id: Tax registration number (VAT, EIN, GSTIN…), free text — no format check.
          address: Billing address. Every field is optional.
        """
        return await self._client._request(
            RequestSpec(
                method="PATCH",
                path=f"/customers/{path_param('id', id)}",
                body=strip_not_given({"name": name, "email": email, "phone": phone, "tax_id": tax_id, "address": address}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="clients:write",
            ),
            Customer,
            "data",
        )

    async def delete(
        self,
        id: str,
        *,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Customer:
        """
        Archive a customer.

        Archives the customer (`deleted: true`) instead of deleting it: issued invoices reference customers and must keep naming who they were billed to. Archived customers drop out of `GET /customers` but stay readable by id. Archiving an archived customer succeeds and changes nothing.

        `DELETE /customers/{id}` · scope `clients:write`
        """
        return await self._client._request(
            RequestSpec(
                method="DELETE",
                path=f"/customers/{path_param('id', id)}",
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="clients:write",
            ),
            Customer,
            "data",
        )


class CustomersWithRawResponse:
    def __init__(self, resource: Customers) -> None:
        self.list = to_raw_response_wrapper(resource.list)
        self.create = to_raw_response_wrapper(resource.create)
        self.retrieve = to_raw_response_wrapper(resource.retrieve)
        self.update = to_raw_response_wrapper(resource.update)
        self.delete = to_raw_response_wrapper(resource.delete)


class AsyncCustomersWithRawResponse:
    def __init__(self, resource: AsyncCustomers) -> None:
        self.list = async_to_raw_response_wrapper(resource.list)
        self.create = async_to_raw_response_wrapper(resource.create)
        self.retrieve = async_to_raw_response_wrapper(resource.retrieve)
        self.update = async_to_raw_response_wrapper(resource.update)
        self.delete = async_to_raw_response_wrapper(resource.delete)
