# Generated by scripts/sdk-gen/python.ts from api-docs/openapi.json. Do not edit.

"""Invoice items: `client.invoice_items`."""

from __future__ import annotations

from functools import cached_property
from typing import Mapping, Optional, Union

from typing_extensions import Literal

from .._resource import AsyncAPIResource, SyncAPIResource
from .._response import async_to_raw_response_wrapper, to_raw_response_wrapper
from .._types import NOT_GIVEN, NotGiven, RequestSpec
from .._utils import path_param, strip_not_given
from ..pagination import AsyncPagePromise, SyncPage
from ..types import Invoice, InvoiceItem

__all__ = ["AsyncInvoiceItems", "InvoiceItems"]


class InvoiceItems(SyncAPIResource):
    """Invoice items: `client.invoice_items`."""

    @cached_property
    def with_raw_response(self) -> InvoiceItemsWithRawResponse:
        """The same methods, returning the raw response: `.with_raw_response.<method>(...)` → `.parse()`, `.headers`, `.request_id`."""
        return InvoiceItemsWithRawResponse(self)

    def list(
        self,
        *,
        invoice: str,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> SyncPage[InvoiceItem]:
        """
        List invoice items.

        Returns every line of one invoice, in order (not paginated). `invoice` is required.

        `GET /invoice-items` · scope `invoices:read`

        Args:
          invoice: The invoice, `in_…` or UUID.
        """
        return self._client._request_page(
            RequestSpec(
                method="GET",
                path="/invoice-items",
                query=strip_not_given({"invoice": invoice}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:read",
            ),
            InvoiceItem,
        )

    def create(
        self,
        *,
        invoice: str,
        price: Union[str, NotGiven] = NOT_GIVEN,
        description: Union[str, NotGiven] = NOT_GIVEN,
        quantity: Union[float, NotGiven] = NOT_GIVEN,
        unit: Union[Literal["NOS", "PCS", "KGS", "GMS", "LTR", "MTR", "SQF", "SQM", "HRS", "DAY", "MON", "BOX", "SET", "OTH"], NotGiven] = NOT_GIVEN,
        unit_amount: Union[int, NotGiven] = NOT_GIVEN,
        discount_percent: Union[float, NotGiven] = NOT_GIVEN,
        tax_rate: Union[float, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Invoice:
        """
        Add an invoice item.

        Appends one line to a draft: either a `price`, or `description` + `unit_amount`. Totals are recomputed, so the response is the whole invoice; every line gets a new id. Finalized invoices return `409`. Emits `invoice.updated`.

        `POST /invoice-items` · scope `invoices:write` · idempotent (automatic key)

        Args:
          invoice: The draft to append to, `in_…` or UUID.
          price: A catalog price, `price_…` or UUID. Its product name, unit amount and tax rate fill any of `description`, `unit_amount`, `tax_rate` you omit. Its currency must match the invoice.
          description: What you are billing for. Required unless `price` is given.
          quantity: Quantity, greater than zero. Defaults to 1.
          unit: Unit of measure. Defaults to `NOS` (numbers).
          unit_amount: Price per unit in integer minor units of the invoice currency. Required unless `price` is given.
          discount_percent: Discount percentage, 0–100, applied before tax. Defaults to 0.
          tax_rate: Tax percentage, 0–100, added on top. Defaults to the price’s rate, or 0 on ad-hoc lines.
        """
        return self._client._request(
            RequestSpec(
                method="POST",
                path="/invoice-items",
                body=strip_not_given({"invoice": invoice, "price": price, "description": description, "quantity": quantity, "unit": unit, "unit_amount": unit_amount, "discount_percent": discount_percent, "tax_rate": tax_rate}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:write",
            ),
            Invoice,
            "data",
        )

    def retrieve(
        self,
        id: str,
        *,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> InvoiceItem:
        """
        Retrieve an invoice item.

        Returns one line by `ii_…` id or UUID, from any of your invoices.

        `GET /invoice-items/{id}` · scope `invoices:read`
        """
        return self._client._request(
            RequestSpec(
                method="GET",
                path=f"/invoice-items/{path_param('id', id)}",
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:read",
            ),
            InvoiceItem,
            "data",
        )

    def delete(
        self,
        id: str,
        *,
        invoice: Union[str, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Invoice:
        """
        Remove an invoice item.

        Removes one line from a draft and returns the whole recomputed invoice. A draft always keeps at least one line (`409` for the last one); finalized invoices return `409`. Pass `invoice` to scope the lookup to one invoice. Emits `invoice.updated`.

        `DELETE /invoice-items/{id}` · scope `invoices:write`

        Args:
          invoice: The invoice the line belongs to, `in_…` or UUID. Speeds up the lookup.
        """
        return self._client._request(
            RequestSpec(
                method="DELETE",
                path=f"/invoice-items/{path_param('id', id)}",
                query=strip_not_given({"invoice": invoice}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:write",
            ),
            Invoice,
            "data",
        )


class AsyncInvoiceItems(AsyncAPIResource):
    """Invoice items: `client.invoice_items` (async)."""

    @cached_property
    def with_raw_response(self) -> AsyncInvoiceItemsWithRawResponse:
        """The same methods, returning the raw response: `await .with_raw_response.<method>(...)` → `.parse()`, `.headers`."""
        return AsyncInvoiceItemsWithRawResponse(self)

    def list(
        self,
        *,
        invoice: str,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> AsyncPagePromise[InvoiceItem]:
        """
        List invoice items.

        Returns every line of one invoice, in order (not paginated). `invoice` is required.

        `GET /invoice-items` · scope `invoices:read`

        Args:
          invoice: The invoice, `in_…` or UUID.
        """
        return self._client._request_page(
            RequestSpec(
                method="GET",
                path="/invoice-items",
                query=strip_not_given({"invoice": invoice}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:read",
            ),
            InvoiceItem,
        )

    async def create(
        self,
        *,
        invoice: str,
        price: Union[str, NotGiven] = NOT_GIVEN,
        description: Union[str, NotGiven] = NOT_GIVEN,
        quantity: Union[float, NotGiven] = NOT_GIVEN,
        unit: Union[Literal["NOS", "PCS", "KGS", "GMS", "LTR", "MTR", "SQF", "SQM", "HRS", "DAY", "MON", "BOX", "SET", "OTH"], NotGiven] = NOT_GIVEN,
        unit_amount: Union[int, NotGiven] = NOT_GIVEN,
        discount_percent: Union[float, NotGiven] = NOT_GIVEN,
        tax_rate: Union[float, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Invoice:
        """
        Add an invoice item.

        Appends one line to a draft: either a `price`, or `description` + `unit_amount`. Totals are recomputed, so the response is the whole invoice; every line gets a new id. Finalized invoices return `409`. Emits `invoice.updated`.

        `POST /invoice-items` · scope `invoices:write` · idempotent (automatic key)

        Args:
          invoice: The draft to append to, `in_…` or UUID.
          price: A catalog price, `price_…` or UUID. Its product name, unit amount and tax rate fill any of `description`, `unit_amount`, `tax_rate` you omit. Its currency must match the invoice.
          description: What you are billing for. Required unless `price` is given.
          quantity: Quantity, greater than zero. Defaults to 1.
          unit: Unit of measure. Defaults to `NOS` (numbers).
          unit_amount: Price per unit in integer minor units of the invoice currency. Required unless `price` is given.
          discount_percent: Discount percentage, 0–100, applied before tax. Defaults to 0.
          tax_rate: Tax percentage, 0–100, added on top. Defaults to the price’s rate, or 0 on ad-hoc lines.
        """
        return await self._client._request(
            RequestSpec(
                method="POST",
                path="/invoice-items",
                body=strip_not_given({"invoice": invoice, "price": price, "description": description, "quantity": quantity, "unit": unit, "unit_amount": unit_amount, "discount_percent": discount_percent, "tax_rate": tax_rate}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:write",
            ),
            Invoice,
            "data",
        )

    async def retrieve(
        self,
        id: str,
        *,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> InvoiceItem:
        """
        Retrieve an invoice item.

        Returns one line by `ii_…` id or UUID, from any of your invoices.

        `GET /invoice-items/{id}` · scope `invoices:read`
        """
        return await self._client._request(
            RequestSpec(
                method="GET",
                path=f"/invoice-items/{path_param('id', id)}",
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:read",
            ),
            InvoiceItem,
            "data",
        )

    async def delete(
        self,
        id: str,
        *,
        invoice: Union[str, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Invoice:
        """
        Remove an invoice item.

        Removes one line from a draft and returns the whole recomputed invoice. A draft always keeps at least one line (`409` for the last one); finalized invoices return `409`. Pass `invoice` to scope the lookup to one invoice. Emits `invoice.updated`.

        `DELETE /invoice-items/{id}` · scope `invoices:write`

        Args:
          invoice: The invoice the line belongs to, `in_…` or UUID. Speeds up the lookup.
        """
        return await self._client._request(
            RequestSpec(
                method="DELETE",
                path=f"/invoice-items/{path_param('id', id)}",
                query=strip_not_given({"invoice": invoice}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:write",
            ),
            Invoice,
            "data",
        )


class InvoiceItemsWithRawResponse:
    def __init__(self, resource: InvoiceItems) -> None:
        self.list = to_raw_response_wrapper(resource.list)
        self.create = to_raw_response_wrapper(resource.create)
        self.retrieve = to_raw_response_wrapper(resource.retrieve)
        self.delete = to_raw_response_wrapper(resource.delete)


class AsyncInvoiceItemsWithRawResponse:
    def __init__(self, resource: AsyncInvoiceItems) -> None:
        self.list = async_to_raw_response_wrapper(resource.list)
        self.create = async_to_raw_response_wrapper(resource.create)
        self.retrieve = async_to_raw_response_wrapper(resource.retrieve)
        self.delete = async_to_raw_response_wrapper(resource.delete)
