# Generated by scripts/sdk-gen/python.ts from api-docs/openapi.json. Do not edit.

"""Invoices: `client.invoices`."""

from __future__ import annotations

import datetime
from functools import cached_property
from typing import Mapping, Optional, Sequence, Union

from typing_extensions import Literal

from .._resource import AsyncAPIResource, SyncAPIResource
from .._response import async_to_raw_response_wrapper, to_raw_response_wrapper
from .._retry import build_url
from .._types import NOT_GIVEN, NotGiven, RequestSpec
from .._utils import path_param, strip_not_given
from ..pagination import AsyncPagePromise, SyncPage
from ..types import Invoice, InvoiceEvent, InvoiceLineInput, InvoiceSendResponse
from ..types.params import InvoiceLineInputParam

__all__ = ["AsyncInvoices", "Invoices"]


class Invoices(SyncAPIResource):
    """Invoices: `client.invoices`."""

    @cached_property
    def with_raw_response(self) -> InvoicesWithRawResponse:
        """The same methods, returning the raw response: `.with_raw_response.<method>(...)` → `.parse()`, `.headers`, `.request_id`."""
        return InvoicesWithRawResponse(self)

    def list(
        self,
        *,
        cursor: Union[str, NotGiven] = NOT_GIVEN,
        limit: Union[int, NotGiven] = NOT_GIVEN,
        status: Union[Literal["draft", "open", "paid", "overdue", "void"], NotGiven] = NOT_GIVEN,
        customer: Union[str, NotGiven] = NOT_GIVEN,
        from_: Union[str, datetime.date, NotGiven] = NOT_GIVEN,
        to: Union[str, datetime.date, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> SyncPage[Invoice]:
        """
        List invoices.

        Returns invoices newest first, cursor-paginated, without `lines`. `status=overdue` selects open invoices whose `due_date` is before today (UTC); `status=open` returns every open invoice, overdue ones included. An unknown `customer` is a `404`.

        `GET /invoices` · scope `invoices:read`

        Args:
          cursor: The `next_cursor` from the previous page. Opaque — do not build it yourself.
          limit: Page size, 1–100. Defaults to 25.
          status: Only invoices in this status. Other values are ignored.
          customer: Only invoices billed to this customer, `cus_…` or UUID.
          from_: Only invoices issued on or after this date (`YYYY-MM-DD`).
          to: Only invoices issued on or before this date (`YYYY-MM-DD`).
        """
        return self._client._request_page(
            RequestSpec(
                method="GET",
                path="/invoices",
                query=strip_not_given({"cursor": cursor, "limit": limit, "status": status, "customer": customer, "from": from_, "to": to}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:read",
            ),
            Invoice,
        )

    def create(
        self,
        *,
        customer: str,
        currency: Union[str, NotGiven] = NOT_GIVEN,
        collection_method: Union[Literal["charge_automatically", "send_invoice"], NotGiven] = NOT_GIVEN,
        due_date: Union[str, datetime.date, NotGiven] = NOT_GIVEN,
        days_until_due: Union[int, NotGiven] = NOT_GIVEN,
        description: Union[str, NotGiven] = NOT_GIVEN,
        footer: Union[str, NotGiven] = NOT_GIVEN,
        items: Union[Sequence[Union[InvoiceLineInputParam, InvoiceLineInput]], NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Invoice:
        """
        Create a draft invoice.

        Creates a `draft` for an existing customer. Each line is either a catalog `price` (description, amount and tax rate are borrowed from it) or an ad-hoc `description` + `unit_amount`. Totals are always computed server-side from the lines. The issue date is today; `currency` defaults to your business currency.

        `POST /invoices` · scope `invoices:write` · idempotent (automatic key)

        Args:
          customer: The customer to bill, `cus_…` or UUID. Must already exist (`POST /customers`).
          currency: ISO 4217 code. Defaults to your business currency.
          collection_method: Defaults to `send_invoice`. Informational today.
          due_date: Due date, `YYYY-MM-DD`. `""` clears it.
          days_until_due: Alternative to `due_date` on create only: issue date + N days (0–365). Ignored on update.
          description: Notes printed on the invoice.
          footer: Terms printed at the foot of the invoice.
          items: The lines, at least one. On update, replaces every existing line; omit to keep them.
        """
        return self._client._request(
            RequestSpec(
                method="POST",
                path="/invoices",
                body=strip_not_given({"customer": customer, "currency": currency, "collection_method": collection_method, "due_date": due_date, "days_until_due": days_until_due, "description": description, "footer": footer, "items": items}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:write",
            ),
            Invoice,
            "data",
        )

    def retrieve(
        self,
        id: str,
        *,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Invoice:
        """
        Retrieve an invoice.

        Returns one invoice by `in_…` id or UUID, with its `lines`. `status` reflects `overdue` at the moment of reading.

        `GET /invoices/{id}` · scope `invoices:read`
        """
        return self._client._request(
            RequestSpec(
                method="GET",
                path=f"/invoices/{path_param('id', id)}",
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:read",
            ),
            Invoice,
            "data",
        )

    def update(
        self,
        id: str,
        *,
        customer: Union[str, NotGiven] = NOT_GIVEN,
        currency: Union[str, NotGiven] = NOT_GIVEN,
        collection_method: Union[Literal["charge_automatically", "send_invoice"], NotGiven] = NOT_GIVEN,
        due_date: Union[str, datetime.date, NotGiven] = NOT_GIVEN,
        days_until_due: Union[int, NotGiven] = NOT_GIVEN,
        description: Union[str, NotGiven] = NOT_GIVEN,
        footer: Union[str, NotGiven] = NOT_GIVEN,
        items: Union[Sequence[Union[InvoiceLineInputParam, InvoiceLineInput]], NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Invoice:
        """
        Update a draft invoice.

        Drafts only. A partial update: send only the fields to change — omitted ones (`customer` included) keep their stored value, and `items`, when sent, replaces every line (omit it to keep them). Totals are recomputed and line ids change. Once finalized an invoice is frozen — the customer may already have the PDF — and this returns `409`. Emits `invoice.updated`.

        `PATCH /invoices/{id}` · scope `invoices:write`

        Args:
          customer: Bill a different customer, `cus_…` or UUID. Omit to keep the current one.
          currency: ISO 4217 code. Defaults to your business currency.
          collection_method: Defaults to `send_invoice`. Informational today.
          due_date: Due date, `YYYY-MM-DD`. `""` clears it.
          days_until_due: Alternative to `due_date` on create only: issue date + N days (0–365). Ignored on update.
          description: Notes printed on the invoice.
          footer: Terms printed at the foot of the invoice.
          items: The lines, at least one. On update, replaces every existing line; omit to keep them.
        """
        return self._client._request(
            RequestSpec(
                method="PATCH",
                path=f"/invoices/{path_param('id', id)}",
                body=strip_not_given({"customer": customer, "currency": currency, "collection_method": collection_method, "due_date": due_date, "days_until_due": days_until_due, "description": description, "footer": footer, "items": items}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:write",
            ),
            Invoice,
            "data",
        )

    def delete(
        self,
        id: str,
        *,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> None:
        """
        Delete a draft invoice.

        Permanently deletes a draft. A finalized invoice can never be deleted — its number belongs to a consecutive series, and a gap reads as a hidden sale. Void it instead.

        `DELETE /invoices/{id}` · scope `invoices:write`
        """
        self._client._request_none(
            RequestSpec(
                method="DELETE",
                path=f"/invoices/{path_param('id', id)}",
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:write",
            ),
        )

    def finalize(
        self,
        id: str,
        *,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Invoice:
        """
        Finalize an invoice.

        Assigns the next permanent number in your series (e.g. `INV-0042`) and moves the draft to `open`. The draft must have at least one line. Finalizing an invoice that already has a number returns it unchanged with the same number — a retry can never burn a second one. Does not email the customer (see `/send`). Emits `invoice.finalized`.

        `POST /invoices/{id}/finalize` · scope `invoices:finalize` · idempotent (automatic key)
        """
        return self._client._request(
            RequestSpec(
                method="POST",
                path=f"/invoices/{path_param('id', id)}/finalize",
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:finalize",
            ),
            Invoice,
            "data",
        )

    def send(
        self,
        id: str,
        *,
        to: Union[str, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> InvoiceSendResponse:
        """
        Send an invoice.

        Emails the invoice PDF and a link to the public invoice page, via Resend, to `to` or else the customer email recorded on the invoice. A draft is finalized first (this scope covers that — `invoices:finalize` is not needed). Open and paid invoices can be re-sent; void ones cannot.

        `POST /invoices/{id}/send` · scope `invoices:send` · idempotent (automatic key)

        Args:
          to: Recipient email. Defaults to the customer email recorded on the invoice; one of the two is required.
        """
        return self._client._request(
            RequestSpec(
                method="POST",
                path=f"/invoices/{path_param('id', id)}/send",
                body=strip_not_given({"to": to}) or None,
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:send",
            ),
            InvoiceSendResponse,
            "body",
        )

    def pay(
        self,
        id: str,
        *,
        paid_on: Union[str, NotGiven] = NOT_GIVEN,
        reference: Union[str, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Invoice:
        """
        Mark an invoice paid.

        Records that an `open` (or overdue) invoice was paid outside Invoice-AI — no money moves. Drafts, void and already-paid invoices return `409`. Sets `paid_at` and `amount_due: 0`. The response omits `lines`. Emits `invoice.paid`, with `reference` in the event meta.

        `POST /invoices/{id}/pay` · scope `payments:write` · idempotent (automatic key)

        Args:
          paid_on: When payment was received (ISO 8601 date or timestamp). Defaults to now.
          reference: Your payment reference (cheque number, bank transfer id). Recorded on the `invoice.paid` event.
        """
        return self._client._request(
            RequestSpec(
                method="POST",
                path=f"/invoices/{path_param('id', id)}/pay",
                body=strip_not_given({"paid_on": paid_on, "reference": reference}) or None,
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="payments:write",
            ),
            Invoice,
            "data",
        )

    def void(
        self,
        id: str,
        *,
        reason: str,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Invoice:
        """
        Void an invoice.

        Voids an `open` (or overdue) invoice with a reason. The number stays on the record — an auditor seeing 0041 then 0043 needs to find 0042 voided, not missing. A paid invoice cannot be voided (it needs a credit note); a draft should be deleted instead. The response omits `lines`. Emits `invoice.voided`.

        `POST /invoices/{id}/void` · scope `invoices:finalize` · idempotent (automatic key)

        Args:
          reason: Why the invoice is void. Required and non-blank; stored as `void_reason`.
        """
        return self._client._request(
            RequestSpec(
                method="POST",
                path=f"/invoices/{path_param('id', id)}/void",
                body=strip_not_given({"reason": reason}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:finalize",
            ),
            Invoice,
            "data",
        )

    def pdf(
        self,
        id: str,
        *,
        download: Union[Literal["1"], NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> bytes:
        """
        Download an invoice PDF.

        Returns the PDF bytes (not a link), rendered on demand from the current invoice, so it is always up to date. Works for drafts too (without a number). Served inline; pass `download=1` for `Content-Disposition: attachment`. Not cacheable (`Cache-Control: private, no-store`).

        `GET /invoices/{id}/pdf` · scope `invoices:read`

        Args:
          download: `1` to download as an attachment instead of displaying inline.
        """
        return self._client._request_bytes(
            RequestSpec(
                method="GET",
                path=f"/invoices/{path_param('id', id)}/pdf",
                query=strip_not_given({"download": download}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                accept="application/pdf",
                required_scope="invoices:read",
            ),
        )

    def pdf_url(self, id: str, *, download: Union[Literal["1"], NotGiven] = NOT_GIVEN) -> str:
        """The absolute URL of `GET /invoices/{id}/pdf`. Fetching it still needs `Authorization: Bearer <key>`."""
        return build_url(self._client.base_url, f"/invoices/{path_param('id', id)}/pdf", strip_not_given({"download": download}))

    def events(
        self,
        id: str,
        *,
        cursor: Union[str, NotGiven] = NOT_GIVEN,
        limit: Union[int, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> SyncPage[InvoiceEvent]:
        """
        List invoice events.

        Returns the history of one invoice, newest first, cursor-paginated: created, updated, finalized, emailed, viewed, downloaded, paid, voided. `invoice.viewed` and `invoice.downloaded` are recorded when the customer opens the public link — the way to tell they actually looked at it.

        `GET /invoices/{id}/events` · scope `invoices:read`

        Args:
          cursor: The `next_cursor` from the previous page. Opaque — do not build it yourself.
          limit: Page size, 1–100. Defaults to 25.
        """
        return self._client._request_page(
            RequestSpec(
                method="GET",
                path=f"/invoices/{path_param('id', id)}/events",
                query=strip_not_given({"cursor": cursor, "limit": limit}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:read",
            ),
            InvoiceEvent,
        )


class AsyncInvoices(AsyncAPIResource):
    """Invoices: `client.invoices` (async)."""

    @cached_property
    def with_raw_response(self) -> AsyncInvoicesWithRawResponse:
        """The same methods, returning the raw response: `await .with_raw_response.<method>(...)` → `.parse()`, `.headers`."""
        return AsyncInvoicesWithRawResponse(self)

    def list(
        self,
        *,
        cursor: Union[str, NotGiven] = NOT_GIVEN,
        limit: Union[int, NotGiven] = NOT_GIVEN,
        status: Union[Literal["draft", "open", "paid", "overdue", "void"], NotGiven] = NOT_GIVEN,
        customer: Union[str, NotGiven] = NOT_GIVEN,
        from_: Union[str, datetime.date, NotGiven] = NOT_GIVEN,
        to: Union[str, datetime.date, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> AsyncPagePromise[Invoice]:
        """
        List invoices.

        Returns invoices newest first, cursor-paginated, without `lines`. `status=overdue` selects open invoices whose `due_date` is before today (UTC); `status=open` returns every open invoice, overdue ones included. An unknown `customer` is a `404`.

        `GET /invoices` · scope `invoices:read`

        Args:
          cursor: The `next_cursor` from the previous page. Opaque — do not build it yourself.
          limit: Page size, 1–100. Defaults to 25.
          status: Only invoices in this status. Other values are ignored.
          customer: Only invoices billed to this customer, `cus_…` or UUID.
          from_: Only invoices issued on or after this date (`YYYY-MM-DD`).
          to: Only invoices issued on or before this date (`YYYY-MM-DD`).
        """
        return self._client._request_page(
            RequestSpec(
                method="GET",
                path="/invoices",
                query=strip_not_given({"cursor": cursor, "limit": limit, "status": status, "customer": customer, "from": from_, "to": to}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:read",
            ),
            Invoice,
        )

    async def create(
        self,
        *,
        customer: str,
        currency: Union[str, NotGiven] = NOT_GIVEN,
        collection_method: Union[Literal["charge_automatically", "send_invoice"], NotGiven] = NOT_GIVEN,
        due_date: Union[str, datetime.date, NotGiven] = NOT_GIVEN,
        days_until_due: Union[int, NotGiven] = NOT_GIVEN,
        description: Union[str, NotGiven] = NOT_GIVEN,
        footer: Union[str, NotGiven] = NOT_GIVEN,
        items: Union[Sequence[Union[InvoiceLineInputParam, InvoiceLineInput]], NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Invoice:
        """
        Create a draft invoice.

        Creates a `draft` for an existing customer. Each line is either a catalog `price` (description, amount and tax rate are borrowed from it) or an ad-hoc `description` + `unit_amount`. Totals are always computed server-side from the lines. The issue date is today; `currency` defaults to your business currency.

        `POST /invoices` · scope `invoices:write` · idempotent (automatic key)

        Args:
          customer: The customer to bill, `cus_…` or UUID. Must already exist (`POST /customers`).
          currency: ISO 4217 code. Defaults to your business currency.
          collection_method: Defaults to `send_invoice`. Informational today.
          due_date: Due date, `YYYY-MM-DD`. `""` clears it.
          days_until_due: Alternative to `due_date` on create only: issue date + N days (0–365). Ignored on update.
          description: Notes printed on the invoice.
          footer: Terms printed at the foot of the invoice.
          items: The lines, at least one. On update, replaces every existing line; omit to keep them.
        """
        return await self._client._request(
            RequestSpec(
                method="POST",
                path="/invoices",
                body=strip_not_given({"customer": customer, "currency": currency, "collection_method": collection_method, "due_date": due_date, "days_until_due": days_until_due, "description": description, "footer": footer, "items": items}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:write",
            ),
            Invoice,
            "data",
        )

    async def retrieve(
        self,
        id: str,
        *,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Invoice:
        """
        Retrieve an invoice.

        Returns one invoice by `in_…` id or UUID, with its `lines`. `status` reflects `overdue` at the moment of reading.

        `GET /invoices/{id}` · scope `invoices:read`
        """
        return await self._client._request(
            RequestSpec(
                method="GET",
                path=f"/invoices/{path_param('id', id)}",
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:read",
            ),
            Invoice,
            "data",
        )

    async def update(
        self,
        id: str,
        *,
        customer: Union[str, NotGiven] = NOT_GIVEN,
        currency: Union[str, NotGiven] = NOT_GIVEN,
        collection_method: Union[Literal["charge_automatically", "send_invoice"], NotGiven] = NOT_GIVEN,
        due_date: Union[str, datetime.date, NotGiven] = NOT_GIVEN,
        days_until_due: Union[int, NotGiven] = NOT_GIVEN,
        description: Union[str, NotGiven] = NOT_GIVEN,
        footer: Union[str, NotGiven] = NOT_GIVEN,
        items: Union[Sequence[Union[InvoiceLineInputParam, InvoiceLineInput]], NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Invoice:
        """
        Update a draft invoice.

        Drafts only. A partial update: send only the fields to change — omitted ones (`customer` included) keep their stored value, and `items`, when sent, replaces every line (omit it to keep them). Totals are recomputed and line ids change. Once finalized an invoice is frozen — the customer may already have the PDF — and this returns `409`. Emits `invoice.updated`.

        `PATCH /invoices/{id}` · scope `invoices:write`

        Args:
          customer: Bill a different customer, `cus_…` or UUID. Omit to keep the current one.
          currency: ISO 4217 code. Defaults to your business currency.
          collection_method: Defaults to `send_invoice`. Informational today.
          due_date: Due date, `YYYY-MM-DD`. `""` clears it.
          days_until_due: Alternative to `due_date` on create only: issue date + N days (0–365). Ignored on update.
          description: Notes printed on the invoice.
          footer: Terms printed at the foot of the invoice.
          items: The lines, at least one. On update, replaces every existing line; omit to keep them.
        """
        return await self._client._request(
            RequestSpec(
                method="PATCH",
                path=f"/invoices/{path_param('id', id)}",
                body=strip_not_given({"customer": customer, "currency": currency, "collection_method": collection_method, "due_date": due_date, "days_until_due": days_until_due, "description": description, "footer": footer, "items": items}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:write",
            ),
            Invoice,
            "data",
        )

    async def delete(
        self,
        id: str,
        *,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> None:
        """
        Delete a draft invoice.

        Permanently deletes a draft. A finalized invoice can never be deleted — its number belongs to a consecutive series, and a gap reads as a hidden sale. Void it instead.

        `DELETE /invoices/{id}` · scope `invoices:write`
        """
        await self._client._request_none(
            RequestSpec(
                method="DELETE",
                path=f"/invoices/{path_param('id', id)}",
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:write",
            ),
        )

    async def finalize(
        self,
        id: str,
        *,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Invoice:
        """
        Finalize an invoice.

        Assigns the next permanent number in your series (e.g. `INV-0042`) and moves the draft to `open`. The draft must have at least one line. Finalizing an invoice that already has a number returns it unchanged with the same number — a retry can never burn a second one. Does not email the customer (see `/send`). Emits `invoice.finalized`.

        `POST /invoices/{id}/finalize` · scope `invoices:finalize` · idempotent (automatic key)
        """
        return await self._client._request(
            RequestSpec(
                method="POST",
                path=f"/invoices/{path_param('id', id)}/finalize",
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:finalize",
            ),
            Invoice,
            "data",
        )

    async def send(
        self,
        id: str,
        *,
        to: Union[str, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> InvoiceSendResponse:
        """
        Send an invoice.

        Emails the invoice PDF and a link to the public invoice page, via Resend, to `to` or else the customer email recorded on the invoice. A draft is finalized first (this scope covers that — `invoices:finalize` is not needed). Open and paid invoices can be re-sent; void ones cannot.

        `POST /invoices/{id}/send` · scope `invoices:send` · idempotent (automatic key)

        Args:
          to: Recipient email. Defaults to the customer email recorded on the invoice; one of the two is required.
        """
        return await self._client._request(
            RequestSpec(
                method="POST",
                path=f"/invoices/{path_param('id', id)}/send",
                body=strip_not_given({"to": to}) or None,
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:send",
            ),
            InvoiceSendResponse,
            "body",
        )

    async def pay(
        self,
        id: str,
        *,
        paid_on: Union[str, NotGiven] = NOT_GIVEN,
        reference: Union[str, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Invoice:
        """
        Mark an invoice paid.

        Records that an `open` (or overdue) invoice was paid outside Invoice-AI — no money moves. Drafts, void and already-paid invoices return `409`. Sets `paid_at` and `amount_due: 0`. The response omits `lines`. Emits `invoice.paid`, with `reference` in the event meta.

        `POST /invoices/{id}/pay` · scope `payments:write` · idempotent (automatic key)

        Args:
          paid_on: When payment was received (ISO 8601 date or timestamp). Defaults to now.
          reference: Your payment reference (cheque number, bank transfer id). Recorded on the `invoice.paid` event.
        """
        return await self._client._request(
            RequestSpec(
                method="POST",
                path=f"/invoices/{path_param('id', id)}/pay",
                body=strip_not_given({"paid_on": paid_on, "reference": reference}) or None,
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="payments:write",
            ),
            Invoice,
            "data",
        )

    async def void(
        self,
        id: str,
        *,
        reason: str,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Invoice:
        """
        Void an invoice.

        Voids an `open` (or overdue) invoice with a reason. The number stays on the record — an auditor seeing 0041 then 0043 needs to find 0042 voided, not missing. A paid invoice cannot be voided (it needs a credit note); a draft should be deleted instead. The response omits `lines`. Emits `invoice.voided`.

        `POST /invoices/{id}/void` · scope `invoices:finalize` · idempotent (automatic key)

        Args:
          reason: Why the invoice is void. Required and non-blank; stored as `void_reason`.
        """
        return await self._client._request(
            RequestSpec(
                method="POST",
                path=f"/invoices/{path_param('id', id)}/void",
                body=strip_not_given({"reason": reason}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:finalize",
            ),
            Invoice,
            "data",
        )

    async def pdf(
        self,
        id: str,
        *,
        download: Union[Literal["1"], NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> bytes:
        """
        Download an invoice PDF.

        Returns the PDF bytes (not a link), rendered on demand from the current invoice, so it is always up to date. Works for drafts too (without a number). Served inline; pass `download=1` for `Content-Disposition: attachment`. Not cacheable (`Cache-Control: private, no-store`).

        `GET /invoices/{id}/pdf` · scope `invoices:read`

        Args:
          download: `1` to download as an attachment instead of displaying inline.
        """
        return await self._client._request_bytes(
            RequestSpec(
                method="GET",
                path=f"/invoices/{path_param('id', id)}/pdf",
                query=strip_not_given({"download": download}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                accept="application/pdf",
                required_scope="invoices:read",
            ),
        )

    def pdf_url(self, id: str, *, download: Union[Literal["1"], NotGiven] = NOT_GIVEN) -> str:
        """The absolute URL of `GET /invoices/{id}/pdf`. Fetching it still needs `Authorization: Bearer <key>`."""
        return build_url(self._client.base_url, f"/invoices/{path_param('id', id)}/pdf", strip_not_given({"download": download}))

    def events(
        self,
        id: str,
        *,
        cursor: Union[str, NotGiven] = NOT_GIVEN,
        limit: Union[int, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> AsyncPagePromise[InvoiceEvent]:
        """
        List invoice events.

        Returns the history of one invoice, newest first, cursor-paginated: created, updated, finalized, emailed, viewed, downloaded, paid, voided. `invoice.viewed` and `invoice.downloaded` are recorded when the customer opens the public link — the way to tell they actually looked at it.

        `GET /invoices/{id}/events` · scope `invoices:read`

        Args:
          cursor: The `next_cursor` from the previous page. Opaque — do not build it yourself.
          limit: Page size, 1–100. Defaults to 25.
        """
        return self._client._request_page(
            RequestSpec(
                method="GET",
                path=f"/invoices/{path_param('id', id)}/events",
                query=strip_not_given({"cursor": cursor, "limit": limit}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="invoices:read",
            ),
            InvoiceEvent,
        )


class InvoicesWithRawResponse:
    def __init__(self, resource: Invoices) -> None:
        self.list = to_raw_response_wrapper(resource.list)
        self.create = to_raw_response_wrapper(resource.create)
        self.retrieve = to_raw_response_wrapper(resource.retrieve)
        self.update = to_raw_response_wrapper(resource.update)
        self.delete = to_raw_response_wrapper(resource.delete)
        self.finalize = to_raw_response_wrapper(resource.finalize)
        self.send = to_raw_response_wrapper(resource.send)
        self.pay = to_raw_response_wrapper(resource.pay)
        self.void = to_raw_response_wrapper(resource.void)
        self.pdf = to_raw_response_wrapper(resource.pdf)
        self.events = to_raw_response_wrapper(resource.events)


class AsyncInvoicesWithRawResponse:
    def __init__(self, resource: AsyncInvoices) -> None:
        self.list = async_to_raw_response_wrapper(resource.list)
        self.create = async_to_raw_response_wrapper(resource.create)
        self.retrieve = async_to_raw_response_wrapper(resource.retrieve)
        self.update = async_to_raw_response_wrapper(resource.update)
        self.delete = async_to_raw_response_wrapper(resource.delete)
        self.finalize = async_to_raw_response_wrapper(resource.finalize)
        self.send = async_to_raw_response_wrapper(resource.send)
        self.pay = async_to_raw_response_wrapper(resource.pay)
        self.void = async_to_raw_response_wrapper(resource.void)
        self.pdf = async_to_raw_response_wrapper(resource.pdf)
        self.events = async_to_raw_response_wrapper(resource.events)
