# Generated by scripts/sdk-gen/python.ts from api-docs/openapi.json. Do not edit.

"""Prices: `client.prices`."""

from __future__ import annotations

from functools import cached_property
from typing import Mapping, Optional, Union

from typing_extensions import Literal

from .._resource import AsyncAPIResource, SyncAPIResource
from .._response import async_to_raw_response_wrapper, to_raw_response_wrapper
from .._types import NOT_GIVEN, NotGiven, RequestSpec
from .._utils import path_param, strip_not_given
from ..pagination import AsyncPagePromise, SyncPage
from ..types import Price, PriceCreateRecurring, PriceUpdateRecurring
from ..types.params import PriceCreateRecurringParam, PriceUpdateRecurringParam

__all__ = ["AsyncPrices", "Prices"]


class Prices(SyncAPIResource):
    """Prices: `client.prices`."""

    @cached_property
    def with_raw_response(self) -> PricesWithRawResponse:
        """The same methods, returning the raw response: `.with_raw_response.<method>(...)` → `.parse()`, `.headers`, `.request_id`."""
        return PricesWithRawResponse(self)

    def list(
        self,
        *,
        cursor: Union[str, NotGiven] = NOT_GIVEN,
        limit: Union[int, NotGiven] = NOT_GIVEN,
        product: Union[str, NotGiven] = NOT_GIVEN,
        active: Union[bool, NotGiven] = NOT_GIVEN,
        currency: Union[str, NotGiven] = NOT_GIVEN,
        type: Union[Literal["one_time", "recurring"], NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> SyncPage[Price]:
        """
        List prices.

        Returns prices newest first, cursor-paginated, optionally filtered by product, active flag, currency or type. An unknown `product` is a `404`, not an empty page.

        `GET /prices` · scope `products:read`

        Args:
          cursor: The `next_cursor` from the previous page. Opaque — do not build it yourself.
          limit: Page size, 1–100. Defaults to 25.
          product: Only prices of this product, `prod_…` or UUID.
          active: `true` for active prices only, `false` for archived only. Omit for both.
          currency: ISO 4217 code, case-insensitive.
          type: Only prices of this type. Other values are ignored.
        """
        return self._client._request_page(
            RequestSpec(
                method="GET",
                path="/prices",
                query=strip_not_given({"cursor": cursor, "limit": limit, "product": product, "active": active, "currency": currency, "type": type}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="products:read",
            ),
            Price,
        )

    def create(
        self,
        *,
        product: str,
        unit_amount: int,
        currency: str,
        nickname: Union[str, NotGiven] = NOT_GIVEN,
        type: Union[Literal["one_time", "recurring"], NotGiven] = NOT_GIVEN,
        recurring: Union[PriceCreateRecurringParam, PriceCreateRecurring, NotGiven] = NOT_GIVEN,
        tax_rate: Union[float, NotGiven] = NOT_GIVEN,
        active: Union[bool, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Price:
        """
        Create a price.

        Adds a price to a product. `unit_amount` is integer minor units. A `recurring` price needs `recurring.interval`; it is stored for reporting — nothing auto-bills yet.

        `POST /prices` · scope `products:write` · idempotent (automatic key)

        Args:
          product: The parent product, `prod_…` or UUID.
          unit_amount: Price per unit in integer minor units (`2500000` is $25,000.00).
          currency: ISO 4217 code, three letters (uppercased for you). Must match the invoice currency when billed.
          nickname: Internal label, e.g. "Monthly".
          type: `one_time` (default) or `recurring`. `recurring` requires `recurring.interval`.
          recurring: Required when `type` is `recurring`; must be omitted for `one_time`.
          tax_rate: Default tax percentage, 0–100, for lines billed from this price. Defaults to 0.
          active: Whether the price is available. Defaults to `true`.
        """
        return self._client._request(
            RequestSpec(
                method="POST",
                path="/prices",
                body=strip_not_given({"product": product, "unit_amount": unit_amount, "currency": currency, "nickname": nickname, "type": type, "recurring": recurring, "tax_rate": tax_rate, "active": active}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="products:write",
            ),
            Price,
            "data",
        )

    def retrieve(
        self,
        id: str,
        *,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Price:
        """
        Retrieve a price.

        Returns one price by `price_…` id or UUID, whether active or archived.

        `GET /prices/{id}` · scope `products:read`
        """
        return self._client._request(
            RequestSpec(
                method="GET",
                path=f"/prices/{path_param('id', id)}",
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="products:read",
            ),
            Price,
            "data",
        )

    def update(
        self,
        id: str,
        *,
        product: Union[str, NotGiven] = NOT_GIVEN,
        nickname: Union[str, NotGiven, None] = NOT_GIVEN,
        unit_amount: Union[int, NotGiven] = NOT_GIVEN,
        currency: Union[str, NotGiven] = NOT_GIVEN,
        type: Union[Literal["one_time", "recurring"], NotGiven] = NOT_GIVEN,
        recurring: Union[PriceUpdateRecurringParam, PriceUpdateRecurring, NotGiven] = NOT_GIVEN,
        tax_rate: Union[float, NotGiven] = NOT_GIVEN,
        active: Union[bool, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Price:
        """
        Update a price.

        Updates the fields you send and leaves the rest unchanged. The parent product cannot change — sending `product` is a `422`; create a new price instead. Lines on finalized invoices keep the amount they were billed at; a draft with a line from this price picks up the change the next time it is saved.

        `PATCH /prices/{id}` · scope `products:write`

        Args:
          product: Not updatable — sending it is a `422`. Create a new price on the other product instead.
          nickname: Internal label. `null` or `""` clears it.
          unit_amount: Price per unit in integer minor units (`2500000` is $25,000.00).
          currency: ISO 4217 code, three letters (uppercased for you). Must match the invoice currency when billed.
          type: Switching to `one_time` clears the interval; switching to `recurring` needs `recurring.interval` unless one is stored.
          recurring: Required when `type` is `recurring`; must be omitted for `one_time`.
          tax_rate: Default tax percentage, 0–100, for lines billed from this price. Defaults to 0.
          active: `false` archives, `true` restores.
        """
        return self._client._request(
            RequestSpec(
                method="PATCH",
                path=f"/prices/{path_param('id', id)}",
                body=strip_not_given({"product": product, "nickname": nickname, "unit_amount": unit_amount, "currency": currency, "type": type, "recurring": recurring, "tax_rate": tax_rate, "active": active}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="products:write",
            ),
            Price,
            "data",
        )

    def archive(
        self,
        id: str,
        *,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Price:
        """
        Archive a price.

        Sets `active: false`. The price is not deleted, because invoice lines may reference it. Archiving an archived price succeeds and changes nothing. Restore with `PATCH` and `active: true`.

        `DELETE /prices/{id}` · scope `products:write`
        """
        return self._client._request(
            RequestSpec(
                method="DELETE",
                path=f"/prices/{path_param('id', id)}",
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="products:write",
            ),
            Price,
            "data",
        )


class AsyncPrices(AsyncAPIResource):
    """Prices: `client.prices` (async)."""

    @cached_property
    def with_raw_response(self) -> AsyncPricesWithRawResponse:
        """The same methods, returning the raw response: `await .with_raw_response.<method>(...)` → `.parse()`, `.headers`."""
        return AsyncPricesWithRawResponse(self)

    def list(
        self,
        *,
        cursor: Union[str, NotGiven] = NOT_GIVEN,
        limit: Union[int, NotGiven] = NOT_GIVEN,
        product: Union[str, NotGiven] = NOT_GIVEN,
        active: Union[bool, NotGiven] = NOT_GIVEN,
        currency: Union[str, NotGiven] = NOT_GIVEN,
        type: Union[Literal["one_time", "recurring"], NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> AsyncPagePromise[Price]:
        """
        List prices.

        Returns prices newest first, cursor-paginated, optionally filtered by product, active flag, currency or type. An unknown `product` is a `404`, not an empty page.

        `GET /prices` · scope `products:read`

        Args:
          cursor: The `next_cursor` from the previous page. Opaque — do not build it yourself.
          limit: Page size, 1–100. Defaults to 25.
          product: Only prices of this product, `prod_…` or UUID.
          active: `true` for active prices only, `false` for archived only. Omit for both.
          currency: ISO 4217 code, case-insensitive.
          type: Only prices of this type. Other values are ignored.
        """
        return self._client._request_page(
            RequestSpec(
                method="GET",
                path="/prices",
                query=strip_not_given({"cursor": cursor, "limit": limit, "product": product, "active": active, "currency": currency, "type": type}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="products:read",
            ),
            Price,
        )

    async def create(
        self,
        *,
        product: str,
        unit_amount: int,
        currency: str,
        nickname: Union[str, NotGiven] = NOT_GIVEN,
        type: Union[Literal["one_time", "recurring"], NotGiven] = NOT_GIVEN,
        recurring: Union[PriceCreateRecurringParam, PriceCreateRecurring, NotGiven] = NOT_GIVEN,
        tax_rate: Union[float, NotGiven] = NOT_GIVEN,
        active: Union[bool, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Price:
        """
        Create a price.

        Adds a price to a product. `unit_amount` is integer minor units. A `recurring` price needs `recurring.interval`; it is stored for reporting — nothing auto-bills yet.

        `POST /prices` · scope `products:write` · idempotent (automatic key)

        Args:
          product: The parent product, `prod_…` or UUID.
          unit_amount: Price per unit in integer minor units (`2500000` is $25,000.00).
          currency: ISO 4217 code, three letters (uppercased for you). Must match the invoice currency when billed.
          nickname: Internal label, e.g. "Monthly".
          type: `one_time` (default) or `recurring`. `recurring` requires `recurring.interval`.
          recurring: Required when `type` is `recurring`; must be omitted for `one_time`.
          tax_rate: Default tax percentage, 0–100, for lines billed from this price. Defaults to 0.
          active: Whether the price is available. Defaults to `true`.
        """
        return await self._client._request(
            RequestSpec(
                method="POST",
                path="/prices",
                body=strip_not_given({"product": product, "unit_amount": unit_amount, "currency": currency, "nickname": nickname, "type": type, "recurring": recurring, "tax_rate": tax_rate, "active": active}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="products:write",
            ),
            Price,
            "data",
        )

    async def retrieve(
        self,
        id: str,
        *,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Price:
        """
        Retrieve a price.

        Returns one price by `price_…` id or UUID, whether active or archived.

        `GET /prices/{id}` · scope `products:read`
        """
        return await self._client._request(
            RequestSpec(
                method="GET",
                path=f"/prices/{path_param('id', id)}",
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="products:read",
            ),
            Price,
            "data",
        )

    async def update(
        self,
        id: str,
        *,
        product: Union[str, NotGiven] = NOT_GIVEN,
        nickname: Union[str, NotGiven, None] = NOT_GIVEN,
        unit_amount: Union[int, NotGiven] = NOT_GIVEN,
        currency: Union[str, NotGiven] = NOT_GIVEN,
        type: Union[Literal["one_time", "recurring"], NotGiven] = NOT_GIVEN,
        recurring: Union[PriceUpdateRecurringParam, PriceUpdateRecurring, NotGiven] = NOT_GIVEN,
        tax_rate: Union[float, NotGiven] = NOT_GIVEN,
        active: Union[bool, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Price:
        """
        Update a price.

        Updates the fields you send and leaves the rest unchanged. The parent product cannot change — sending `product` is a `422`; create a new price instead. Lines on finalized invoices keep the amount they were billed at; a draft with a line from this price picks up the change the next time it is saved.

        `PATCH /prices/{id}` · scope `products:write`

        Args:
          product: Not updatable — sending it is a `422`. Create a new price on the other product instead.
          nickname: Internal label. `null` or `""` clears it.
          unit_amount: Price per unit in integer minor units (`2500000` is $25,000.00).
          currency: ISO 4217 code, three letters (uppercased for you). Must match the invoice currency when billed.
          type: Switching to `one_time` clears the interval; switching to `recurring` needs `recurring.interval` unless one is stored.
          recurring: Required when `type` is `recurring`; must be omitted for `one_time`.
          tax_rate: Default tax percentage, 0–100, for lines billed from this price. Defaults to 0.
          active: `false` archives, `true` restores.
        """
        return await self._client._request(
            RequestSpec(
                method="PATCH",
                path=f"/prices/{path_param('id', id)}",
                body=strip_not_given({"product": product, "nickname": nickname, "unit_amount": unit_amount, "currency": currency, "type": type, "recurring": recurring, "tax_rate": tax_rate, "active": active}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="products:write",
            ),
            Price,
            "data",
        )

    async def archive(
        self,
        id: str,
        *,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Price:
        """
        Archive a price.

        Sets `active: false`. The price is not deleted, because invoice lines may reference it. Archiving an archived price succeeds and changes nothing. Restore with `PATCH` and `active: true`.

        `DELETE /prices/{id}` · scope `products:write`
        """
        return await self._client._request(
            RequestSpec(
                method="DELETE",
                path=f"/prices/{path_param('id', id)}",
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="products:write",
            ),
            Price,
            "data",
        )


class PricesWithRawResponse:
    def __init__(self, resource: Prices) -> None:
        self.list = to_raw_response_wrapper(resource.list)
        self.create = to_raw_response_wrapper(resource.create)
        self.retrieve = to_raw_response_wrapper(resource.retrieve)
        self.update = to_raw_response_wrapper(resource.update)
        self.archive = to_raw_response_wrapper(resource.archive)


class AsyncPricesWithRawResponse:
    def __init__(self, resource: AsyncPrices) -> None:
        self.list = async_to_raw_response_wrapper(resource.list)
        self.create = async_to_raw_response_wrapper(resource.create)
        self.retrieve = async_to_raw_response_wrapper(resource.retrieve)
        self.update = async_to_raw_response_wrapper(resource.update)
        self.archive = async_to_raw_response_wrapper(resource.archive)
