# Generated by scripts/sdk-gen/python.ts from api-docs/openapi.json. Do not edit.

"""Products: `client.products`."""

from __future__ import annotations

from functools import cached_property
from typing import Mapping, Optional, Sequence, Union

from .._resource import AsyncAPIResource, SyncAPIResource
from .._response import async_to_raw_response_wrapper, to_raw_response_wrapper
from .._types import NOT_GIVEN, NotGiven, RequestSpec
from .._utils import path_param, strip_not_given
from ..pagination import AsyncPagePromise, SyncPage
from ..types import Product

__all__ = ["AsyncProducts", "Products"]


class Products(SyncAPIResource):
    """Products: `client.products`."""

    @cached_property
    def with_raw_response(self) -> ProductsWithRawResponse:
        """The same methods, returning the raw response: `.with_raw_response.<method>(...)` → `.parse()`, `.headers`, `.request_id`."""
        return ProductsWithRawResponse(self)

    def list(
        self,
        *,
        cursor: Union[str, NotGiven] = NOT_GIVEN,
        limit: Union[int, NotGiven] = NOT_GIVEN,
        query: Union[str, NotGiven] = NOT_GIVEN,
        active: Union[bool, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> SyncPage[Product]:
        """
        List products.

        Returns products newest first, cursor-paginated. Archived products are included unless you filter with `active`.

        `GET /products` · scope `products:read`

        Args:
          cursor: The `next_cursor` from the previous page. Opaque — do not build it yourself.
          limit: Page size, 1–100. Defaults to 25.
          query: Case-insensitive substring match on `name`.
          active: `true` for active products only, `false` for archived only. Omit for both.
        """
        return self._client._request_page(
            RequestSpec(
                method="GET",
                path="/products",
                query=strip_not_given({"cursor": cursor, "limit": limit, "query": query, "active": active}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="products:read",
            ),
            Product,
        )

    def create(
        self,
        *,
        name: str,
        description: Union[str, NotGiven] = NOT_GIVEN,
        images: Union[Sequence[str], NotGiven] = NOT_GIVEN,
        active: Union[bool, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Product:
        """
        Create a product.

        Creates a product. Add one or more prices to it with `POST /prices` before billing it.

        `POST /products` · scope `products:write` · idempotent (automatic key)

        Args:
          name: Product name, 1–200 characters. Becomes the default line description.
          description: Longer description.
          images: Up to 8 image URLs.
          active: Whether the product is available. Defaults to `true` on create.
        """
        return self._client._request(
            RequestSpec(
                method="POST",
                path="/products",
                body=strip_not_given({"name": name, "description": description, "images": images, "active": active}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="products:write",
            ),
            Product,
            "data",
        )

    def retrieve(
        self,
        id: str,
        *,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Product:
        """
        Retrieve a product.

        Returns one product by `prod_…` id or UUID, whether active or archived.

        `GET /products/{id}` · scope `products:read`
        """
        return self._client._request(
            RequestSpec(
                method="GET",
                path=f"/products/{path_param('id', id)}",
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="products:read",
            ),
            Product,
            "data",
        )

    def update(
        self,
        id: str,
        *,
        name: Union[str, NotGiven] = NOT_GIVEN,
        description: Union[str, NotGiven, None] = NOT_GIVEN,
        images: Union[Sequence[str], NotGiven] = NOT_GIVEN,
        active: Union[bool, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Product:
        """
        Update a product.

        Updates the fields you send and leaves the rest unchanged — omitted fields are never reset to defaults. Send `active: true` to restore an archived product. Finalized invoices keep the line descriptions they were issued with.

        `PATCH /products/{id}` · scope `products:write`

        Args:
          name: Product name, 1–200 characters. Becomes the default line description.
          description: Longer description. `null` or `""` clears it.
          images: Up to 8 image URLs.
          active: `false` archives, `true` restores.
        """
        return self._client._request(
            RequestSpec(
                method="PATCH",
                path=f"/products/{path_param('id', id)}",
                body=strip_not_given({"name": name, "description": description, "images": images, "active": active}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="products:write",
            ),
            Product,
            "data",
        )

    def archive(
        self,
        id: str,
        *,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Product:
        """
        Archive a product.

        Sets `active: false`. The product is not deleted — its prices and the invoice lines that reference it stay intact. Archiving an archived product succeeds and changes nothing. Restore with `PATCH` and `active: true`.

        `DELETE /products/{id}` · scope `products:write`
        """
        return self._client._request(
            RequestSpec(
                method="DELETE",
                path=f"/products/{path_param('id', id)}",
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="products:write",
            ),
            Product,
            "data",
        )


class AsyncProducts(AsyncAPIResource):
    """Products: `client.products` (async)."""

    @cached_property
    def with_raw_response(self) -> AsyncProductsWithRawResponse:
        """The same methods, returning the raw response: `await .with_raw_response.<method>(...)` → `.parse()`, `.headers`."""
        return AsyncProductsWithRawResponse(self)

    def list(
        self,
        *,
        cursor: Union[str, NotGiven] = NOT_GIVEN,
        limit: Union[int, NotGiven] = NOT_GIVEN,
        query: Union[str, NotGiven] = NOT_GIVEN,
        active: Union[bool, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> AsyncPagePromise[Product]:
        """
        List products.

        Returns products newest first, cursor-paginated. Archived products are included unless you filter with `active`.

        `GET /products` · scope `products:read`

        Args:
          cursor: The `next_cursor` from the previous page. Opaque — do not build it yourself.
          limit: Page size, 1–100. Defaults to 25.
          query: Case-insensitive substring match on `name`.
          active: `true` for active products only, `false` for archived only. Omit for both.
        """
        return self._client._request_page(
            RequestSpec(
                method="GET",
                path="/products",
                query=strip_not_given({"cursor": cursor, "limit": limit, "query": query, "active": active}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="products:read",
            ),
            Product,
        )

    async def create(
        self,
        *,
        name: str,
        description: Union[str, NotGiven] = NOT_GIVEN,
        images: Union[Sequence[str], NotGiven] = NOT_GIVEN,
        active: Union[bool, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Product:
        """
        Create a product.

        Creates a product. Add one or more prices to it with `POST /prices` before billing it.

        `POST /products` · scope `products:write` · idempotent (automatic key)

        Args:
          name: Product name, 1–200 characters. Becomes the default line description.
          description: Longer description.
          images: Up to 8 image URLs.
          active: Whether the product is available. Defaults to `true` on create.
        """
        return await self._client._request(
            RequestSpec(
                method="POST",
                path="/products",
                body=strip_not_given({"name": name, "description": description, "images": images, "active": active}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="products:write",
            ),
            Product,
            "data",
        )

    async def retrieve(
        self,
        id: str,
        *,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Product:
        """
        Retrieve a product.

        Returns one product by `prod_…` id or UUID, whether active or archived.

        `GET /products/{id}` · scope `products:read`
        """
        return await self._client._request(
            RequestSpec(
                method="GET",
                path=f"/products/{path_param('id', id)}",
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="products:read",
            ),
            Product,
            "data",
        )

    async def update(
        self,
        id: str,
        *,
        name: Union[str, NotGiven] = NOT_GIVEN,
        description: Union[str, NotGiven, None] = NOT_GIVEN,
        images: Union[Sequence[str], NotGiven] = NOT_GIVEN,
        active: Union[bool, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Product:
        """
        Update a product.

        Updates the fields you send and leaves the rest unchanged — omitted fields are never reset to defaults. Send `active: true` to restore an archived product. Finalized invoices keep the line descriptions they were issued with.

        `PATCH /products/{id}` · scope `products:write`

        Args:
          name: Product name, 1–200 characters. Becomes the default line description.
          description: Longer description. `null` or `""` clears it.
          images: Up to 8 image URLs.
          active: `false` archives, `true` restores.
        """
        return await self._client._request(
            RequestSpec(
                method="PATCH",
                path=f"/products/{path_param('id', id)}",
                body=strip_not_given({"name": name, "description": description, "images": images, "active": active}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="products:write",
            ),
            Product,
            "data",
        )

    async def archive(
        self,
        id: str,
        *,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> Product:
        """
        Archive a product.

        Sets `active: false`. The product is not deleted — its prices and the invoice lines that reference it stay intact. Archiving an archived product succeeds and changes nothing. Restore with `PATCH` and `active: true`.

        `DELETE /products/{id}` · scope `products:write`
        """
        return await self._client._request(
            RequestSpec(
                method="DELETE",
                path=f"/products/{path_param('id', id)}",
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="products:write",
            ),
            Product,
            "data",
        )


class ProductsWithRawResponse:
    def __init__(self, resource: Products) -> None:
        self.list = to_raw_response_wrapper(resource.list)
        self.create = to_raw_response_wrapper(resource.create)
        self.retrieve = to_raw_response_wrapper(resource.retrieve)
        self.update = to_raw_response_wrapper(resource.update)
        self.archive = to_raw_response_wrapper(resource.archive)


class AsyncProductsWithRawResponse:
    def __init__(self, resource: AsyncProducts) -> None:
        self.list = async_to_raw_response_wrapper(resource.list)
        self.create = async_to_raw_response_wrapper(resource.create)
        self.retrieve = async_to_raw_response_wrapper(resource.retrieve)
        self.update = async_to_raw_response_wrapper(resource.update)
        self.archive = async_to_raw_response_wrapper(resource.archive)
