# Generated by scripts/sdk-gen/python.ts from api-docs/openapi.json. Do not edit.

"""Webhook endpoints: `client.webhook_endpoints`."""

from __future__ import annotations

from functools import cached_property
from typing import Mapping, Optional, Sequence, Union

from typing_extensions import Literal

from .._resource import AsyncAPIResource, SyncAPIResource
from .._response import async_to_raw_response_wrapper, to_raw_response_wrapper
from .._types import NOT_GIVEN, NotGiven, RequestSpec
from .._utils import path_param, strip_not_given
from ..pagination import AsyncPagePromise, SyncPage
from ..types import WebhookEndpoint, WebhookEndpointCreateResult

__all__ = ["AsyncWebhookEndpoints", "WebhookEndpoints"]


class WebhookEndpoints(SyncAPIResource):
    """Webhook endpoints: `client.webhook_endpoints`."""

    @cached_property
    def with_raw_response(self) -> WebhookEndpointsWithRawResponse:
        """The same methods, returning the raw response: `.with_raw_response.<method>(...)` → `.parse()`, `.headers`, `.request_id`."""
        return WebhookEndpointsWithRawResponse(self)

    def list(
        self,
        *,
        cursor: Union[str, NotGiven] = NOT_GIVEN,
        limit: Union[int, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> SyncPage[WebhookEndpoint]:
        """
        List webhook endpoints.

        Returns your webhook endpoints, newest first, cursor-paginated. Signing secrets are never included — only once, at creation.

        `GET /webhook-endpoints` · scope `webhooks:manage`

        Args:
          cursor: The `next_cursor` from the previous page. Opaque — do not build it yourself.
          limit: Page size, 1–100. Defaults to 25.
        """
        return self._client._request_page(
            RequestSpec(
                method="GET",
                path="/webhook-endpoints",
                query=strip_not_given({"cursor": cursor, "limit": limit}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="webhooks:manage",
            ),
            WebhookEndpoint,
        )

    def create(
        self,
        *,
        url: str,
        events: Union[Sequence[Literal["invoice.created", "invoice.updated", "invoice.finalized", "invoice.emailed", "invoice.email_failed", "invoice.viewed", "invoice.downloaded", "invoice.paid", "invoice.voided"]], NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> WebhookEndpointCreateResult:
        """
        Create a webhook endpoint.

        Registers an https URL to receive events. The response carries the signing `secret` (`whsec_` + base64) — the only time it is returned, so store it. The URL must use https and must not resolve to a private, loopback or link-local address.

        `POST /webhook-endpoints` · scope `webhooks:manage` · idempotent (automatic key)

        Args:
          url: An `https://` URL that does not resolve to a private, loopback or link-local address.
          events: Event types to receive. Omit or send `[]` to receive every type, including ones added later.
        """
        return self._client._request(
            RequestSpec(
                method="POST",
                path="/webhook-endpoints",
                body=strip_not_given({"url": url, "events": events}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="webhooks:manage",
            ),
            WebhookEndpointCreateResult,
            "data",
        )

    def delete(
        self,
        id: str,
        *,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> None:
        """
        Delete a webhook endpoint.

        Permanently deletes the endpoint; no further deliveries are made to it. Deleting it again is a `404`, not a silent success — that usually means you are working from a stale list.

        `DELETE /webhook-endpoints/{id}` · scope `webhooks:manage`
        """
        self._client._request_none(
            RequestSpec(
                method="DELETE",
                path=f"/webhook-endpoints/{path_param('id', id)}",
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="webhooks:manage",
            ),
        )


class AsyncWebhookEndpoints(AsyncAPIResource):
    """Webhook endpoints: `client.webhook_endpoints` (async)."""

    @cached_property
    def with_raw_response(self) -> AsyncWebhookEndpointsWithRawResponse:
        """The same methods, returning the raw response: `await .with_raw_response.<method>(...)` → `.parse()`, `.headers`."""
        return AsyncWebhookEndpointsWithRawResponse(self)

    def list(
        self,
        *,
        cursor: Union[str, NotGiven] = NOT_GIVEN,
        limit: Union[int, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> AsyncPagePromise[WebhookEndpoint]:
        """
        List webhook endpoints.

        Returns your webhook endpoints, newest first, cursor-paginated. Signing secrets are never included — only once, at creation.

        `GET /webhook-endpoints` · scope `webhooks:manage`

        Args:
          cursor: The `next_cursor` from the previous page. Opaque — do not build it yourself.
          limit: Page size, 1–100. Defaults to 25.
        """
        return self._client._request_page(
            RequestSpec(
                method="GET",
                path="/webhook-endpoints",
                query=strip_not_given({"cursor": cursor, "limit": limit}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="webhooks:manage",
            ),
            WebhookEndpoint,
        )

    async def create(
        self,
        *,
        url: str,
        events: Union[Sequence[Literal["invoice.created", "invoice.updated", "invoice.finalized", "invoice.emailed", "invoice.email_failed", "invoice.viewed", "invoice.downloaded", "invoice.paid", "invoice.voided"]], NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> WebhookEndpointCreateResult:
        """
        Create a webhook endpoint.

        Registers an https URL to receive events. The response carries the signing `secret` (`whsec_` + base64) — the only time it is returned, so store it. The URL must use https and must not resolve to a private, loopback or link-local address.

        `POST /webhook-endpoints` · scope `webhooks:manage` · idempotent (automatic key)

        Args:
          url: An `https://` URL that does not resolve to a private, loopback or link-local address.
          events: Event types to receive. Omit or send `[]` to receive every type, including ones added later.
        """
        return await self._client._request(
            RequestSpec(
                method="POST",
                path="/webhook-endpoints",
                body=strip_not_given({"url": url, "events": events}),
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="webhooks:manage",
            ),
            WebhookEndpointCreateResult,
            "data",
        )

    async def delete(
        self,
        id: str,
        *,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> None:
        """
        Delete a webhook endpoint.

        Permanently deletes the endpoint; no further deliveries are made to it. Deleting it again is a `404`, not a silent success — that usually means you are working from a stale list.

        `DELETE /webhook-endpoints/{id}` · scope `webhooks:manage`
        """
        await self._client._request_none(
            RequestSpec(
                method="DELETE",
                path=f"/webhook-endpoints/{path_param('id', id)}",
                idempotency_key=idempotency_key,
                timeout=timeout,
                max_retries=max_retries,
                extra_headers=extra_headers,
                required_scope="webhooks:manage",
            ),
        )


class WebhookEndpointsWithRawResponse:
    def __init__(self, resource: WebhookEndpoints) -> None:
        self.list = to_raw_response_wrapper(resource.list)
        self.create = to_raw_response_wrapper(resource.create)
        self.delete = to_raw_response_wrapper(resource.delete)


class AsyncWebhookEndpointsWithRawResponse:
    def __init__(self, resource: AsyncWebhookEndpoints) -> None:
        self.list = async_to_raw_response_wrapper(resource.list)
        self.create = async_to_raw_response_wrapper(resource.create)
        self.delete = async_to_raw_response_wrapper(resource.delete)
