#!/usr/bin/env node
/**
 * Writes api-docs/cli/commands.mdx from the built CLI's own `--help` output,
 * so the command reference can't drift from the code.
 *
 *   pnpm cli:docs            (from the repo root: builds SDK + CLI, then runs this)
 */
import { execFileSync } from 'node:child_process'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const BIN = fileURLToPath(new URL('../dist/index.js', import.meta.url))
const OUT = fileURLToPath(new URL('../../../api-docs/cli/commands.mdx', import.meta.url))

function help(path) {
  return execFileSync(process.execPath, [BIN, ...path, '--help'], {
    encoding: 'utf8',
    env: { ...process.env, NO_COLOR: '1', CI: '1', INVOICE_AI_NO_UPDATE_CHECK: '1', COLUMNS: '80' },
  })
}

/** Subcommand names from the "Commands:" section of a help text. */
function subcommands(text) {
  const lines = text.split('\n')
  const start = lines.findIndex((l) => l === 'Commands:')
  if (start === -1) return []
  const names = []
  for (const line of lines.slice(start + 1)) {
    if (line.trim() === '') break
    const m = line.match(/^ {2}([a-z][\w-]*)/)
    if (m) names.push(m[1])
  }
  return names
}

/** Global options are documented once, on the root command. */
function withoutGlobals(text) {
  return text.replace(/\nGlobal Options:\n(?: {2}.*\n| {4,}.*\n)+/, '\n')
}

const sections = []
function walk(path) {
  const text = help(path)
  sections.push({ path, text: path.length ? withoutGlobals(text) : text })
  for (const name of subcommands(text)) walk([...path, name])
}
walk([])

const body = sections
  .map(({ path, text }) => {
    const title = ['invoice-ai', ...path].join(' ')
    return `## ${title}\n\n\`\`\`text\n${text.trimEnd()}\n\`\`\``
  })
  .join('\n\n')

const mdx = `---
title: "Command reference"
description: "Every invoice-ai command, flag and example, generated from the CLI's own --help output."
---

{/* Generated by \`pnpm cli:docs\` from \`invoice-ai --help\`. Do not edit by hand. */}

Every command accepts the global options shown under \`invoice-ai\` below (\`--json\`, \`--profile\`, \`--api-key\`, \`--yes\`, …).

${body}
`

mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(OUT, mdx)
console.log(`Wrote ${OUT} (${sections.length} commands)`)
