# Generated by scripts/sdk-gen/python.ts from api-docs/openapi.json. Do not edit.

#: OpenAPI `info.version` of the spec this SDK was generated from, sent as `Invoice-AI-Version`.
API_VERSION = "1.0.0"
