# Generated by scripts/sdk-gen/python.ts from api-docs/openapi.json. Do not edit.

"""Every API operation and the SDK method that calls it."""

from __future__ import annotations

from typing import Optional, Tuple

from typing_extensions import TypedDict


class Operation(TypedDict):
    operation_id: str
    http_method: str
    path: str
    resource: str
    method: str
    kind: str
    scope: Optional[str]


OPERATIONS: Tuple[Operation, ...] = (
    {"operation_id": "getBusiness", "http_method": "GET", "path": "/business", "resource": "business", "method": "retrieve", "kind": "data", "scope": "business:read"},
    {"operation_id": "listCustomers", "http_method": "GET", "path": "/customers", "resource": "customers", "method": "list", "kind": "page", "scope": "clients:read"},
    {"operation_id": "createCustomer", "http_method": "POST", "path": "/customers", "resource": "customers", "method": "create", "kind": "data", "scope": "clients:write"},
    {"operation_id": "retrieveCustomer", "http_method": "GET", "path": "/customers/{id}", "resource": "customers", "method": "retrieve", "kind": "data", "scope": "clients:read"},
    {"operation_id": "updateCustomer", "http_method": "PATCH", "path": "/customers/{id}", "resource": "customers", "method": "update", "kind": "data", "scope": "clients:write"},
    {"operation_id": "deleteCustomer", "http_method": "DELETE", "path": "/customers/{id}", "resource": "customers", "method": "delete", "kind": "data", "scope": "clients:write"},
    {"operation_id": "listProducts", "http_method": "GET", "path": "/products", "resource": "products", "method": "list", "kind": "page", "scope": "products:read"},
    {"operation_id": "createProduct", "http_method": "POST", "path": "/products", "resource": "products", "method": "create", "kind": "data", "scope": "products:write"},
    {"operation_id": "retrieveProduct", "http_method": "GET", "path": "/products/{id}", "resource": "products", "method": "retrieve", "kind": "data", "scope": "products:read"},
    {"operation_id": "updateProduct", "http_method": "PATCH", "path": "/products/{id}", "resource": "products", "method": "update", "kind": "data", "scope": "products:write"},
    {"operation_id": "archiveProduct", "http_method": "DELETE", "path": "/products/{id}", "resource": "products", "method": "archive", "kind": "data", "scope": "products:write"},
    {"operation_id": "listPrices", "http_method": "GET", "path": "/prices", "resource": "prices", "method": "list", "kind": "page", "scope": "products:read"},
    {"operation_id": "createPrice", "http_method": "POST", "path": "/prices", "resource": "prices", "method": "create", "kind": "data", "scope": "products:write"},
    {"operation_id": "retrievePrice", "http_method": "GET", "path": "/prices/{id}", "resource": "prices", "method": "retrieve", "kind": "data", "scope": "products:read"},
    {"operation_id": "updatePrice", "http_method": "PATCH", "path": "/prices/{id}", "resource": "prices", "method": "update", "kind": "data", "scope": "products:write"},
    {"operation_id": "archivePrice", "http_method": "DELETE", "path": "/prices/{id}", "resource": "prices", "method": "archive", "kind": "data", "scope": "products:write"},
    {"operation_id": "listInvoices", "http_method": "GET", "path": "/invoices", "resource": "invoices", "method": "list", "kind": "page", "scope": "invoices:read"},
    {"operation_id": "createInvoice", "http_method": "POST", "path": "/invoices", "resource": "invoices", "method": "create", "kind": "data", "scope": "invoices:write"},
    {"operation_id": "retrieveInvoice", "http_method": "GET", "path": "/invoices/{id}", "resource": "invoices", "method": "retrieve", "kind": "data", "scope": "invoices:read"},
    {"operation_id": "updateInvoice", "http_method": "PATCH", "path": "/invoices/{id}", "resource": "invoices", "method": "update", "kind": "data", "scope": "invoices:write"},
    {"operation_id": "deleteInvoice", "http_method": "DELETE", "path": "/invoices/{id}", "resource": "invoices", "method": "delete", "kind": "void", "scope": "invoices:write"},
    {"operation_id": "finalizeInvoice", "http_method": "POST", "path": "/invoices/{id}/finalize", "resource": "invoices", "method": "finalize", "kind": "data", "scope": "invoices:finalize"},
    {"operation_id": "sendInvoice", "http_method": "POST", "path": "/invoices/{id}/send", "resource": "invoices", "method": "send", "kind": "body", "scope": "invoices:send"},
    {"operation_id": "payInvoice", "http_method": "POST", "path": "/invoices/{id}/pay", "resource": "invoices", "method": "pay", "kind": "data", "scope": "payments:write"},
    {"operation_id": "voidInvoice", "http_method": "POST", "path": "/invoices/{id}/void", "resource": "invoices", "method": "void", "kind": "data", "scope": "invoices:finalize"},
    {"operation_id": "retrieveInvoicePdf", "http_method": "GET", "path": "/invoices/{id}/pdf", "resource": "invoices", "method": "pdf", "kind": "binary", "scope": "invoices:read"},
    {"operation_id": "listInvoiceEvents", "http_method": "GET", "path": "/invoices/{id}/events", "resource": "invoices", "method": "events", "kind": "page", "scope": "invoices:read"},
    {"operation_id": "listInvoiceItems", "http_method": "GET", "path": "/invoice-items", "resource": "invoice_items", "method": "list", "kind": "page", "scope": "invoices:read"},
    {"operation_id": "createInvoiceItem", "http_method": "POST", "path": "/invoice-items", "resource": "invoice_items", "method": "create", "kind": "data", "scope": "invoices:write"},
    {"operation_id": "retrieveInvoiceItem", "http_method": "GET", "path": "/invoice-items/{id}", "resource": "invoice_items", "method": "retrieve", "kind": "data", "scope": "invoices:read"},
    {"operation_id": "deleteInvoiceItem", "http_method": "DELETE", "path": "/invoice-items/{id}", "resource": "invoice_items", "method": "delete", "kind": "data", "scope": "invoices:write"},
    {"operation_id": "listWebhookEndpoints", "http_method": "GET", "path": "/webhook-endpoints", "resource": "webhook_endpoints", "method": "list", "kind": "page", "scope": "webhooks:manage"},
    {"operation_id": "createWebhookEndpoint", "http_method": "POST", "path": "/webhook-endpoints", "resource": "webhook_endpoints", "method": "create", "kind": "data", "scope": "webhooks:manage"},
    {"operation_id": "deleteWebhookEndpoint", "http_method": "DELETE", "path": "/webhook-endpoints/{id}", "resource": "webhook_endpoints", "method": "delete", "kind": "void", "scope": "webhooks:manage"},
)
