// Generated by scripts/sdk-gen/ts.ts from api-docs/openapi.json. Do not edit.

import type { APIPromise } from '../core/api-promise'
import { APIResource } from '../core/client'
import type { RequestOptions } from '../core/http'
import type { Business } from '../generated/types'

/** Business: `invoiceai.business`. */
export class BusinessResource extends APIResource {
  /**
   * Retrieve the business profile.
   * Returns the business profile invoices are issued from: legal name, address, tax id, default currency, bank details and invoice prefix. Read-only — the profile is edited in the app.
   * `GET /business` · scope `business:read`
   */
  retrieve(options?: RequestOptions): APIPromise<Business> {
    return this._client._request<Business>({ method: 'GET', path: `/business`, options, requiredScope: 'business:read' }, 'data')
  }
}
