// Generated by scripts/sdk-gen/ts.ts from api-docs/openapi.json. Do not edit.

import type { APIPromise } from '../core/api-promise'
import { APIResource, pathParam } from '../core/client'
import type { RequestOptions } from '../core/http'
import type { PagePromise } from '../core/pagination'
import type { operations } from '../generated/schema'
import type { Customer } from '../generated/types'

export type CustomerListParams = NonNullable<operations['listCustomers']['parameters']['query']>
export type CustomerCreateParams = NonNullable<operations['createCustomer']['requestBody']>['content']['application/json']
export type CustomerUpdateParams = NonNullable<operations['updateCustomer']['requestBody']>['content']['application/json']

/** Customers: `invoiceai.customers`. */
export class Customers extends APIResource {
  /**
   * List customers.
   * Returns customers newest first, cursor-paginated. Archived customers are excluded unless `include_deleted=true`.
   * `GET /customers` · scope `clients:read`
   */
  list(params?: CustomerListParams, options?: RequestOptions): PagePromise<Customer> {
    return this._client._requestPage<Customer>({ method: 'GET', path: `/customers`, query: params, options, requiredScope: 'clients:read' })
  }

  /**
   * Create a customer.
   * Creates a customer you can bill. Only `name` is required. Creating does not deduplicate — two calls with the same name make two customers.
   * `POST /customers` · scope `clients:write` · idempotent (automatic key)
   */
  create(params: CustomerCreateParams, options?: RequestOptions): APIPromise<Customer> {
    return this._client._request<Customer>({ method: 'POST', path: `/customers`, body: params, options, requiredScope: 'clients:write' }, 'data')
  }

  /**
   * Retrieve a customer.
   * Returns one customer by `cus_…` id or UUID, including archived ones (`deleted: true`).
   * `GET /customers/{id}` · scope `clients:read`
   */
  retrieve(id: string, options?: RequestOptions): APIPromise<Customer> {
    return this._client._request<Customer>({ method: 'GET', path: `/customers/${pathParam('id', id)}`, options, requiredScope: 'clients:read' }, 'data')
  }

  /**
   * Update a customer.
   * Updates the fields you send and leaves the rest unchanged. Existing invoices are not affected — each invoice keeps a snapshot of the customer as billed. Naturally idempotent, so no `Idempotency-Key` is needed.
   * `PATCH /customers/{id}` · scope `clients:write`
   */
  update(id: string, params: CustomerUpdateParams, options?: RequestOptions): APIPromise<Customer> {
    return this._client._request<Customer>({ method: 'PATCH', path: `/customers/${pathParam('id', id)}`, body: params, options, requiredScope: 'clients:write' }, 'data')
  }

  /**
   * Archive a customer.
   * Archives the customer (`deleted: true`) instead of deleting it: issued invoices reference customers and must keep naming who they were billed to. Archived customers drop out of `GET /customers` but stay readable by id. Archiving an archived customer succeeds and changes nothing.
   * `DELETE /customers/{id}` · scope `clients:write`
   */
  del(id: string, options?: RequestOptions): APIPromise<Customer> {
    return this._client._request<Customer>({ method: 'DELETE', path: `/customers/${pathParam('id', id)}`, options, requiredScope: 'clients:write' }, 'data')
  }
}
