// Generated by scripts/sdk-gen/ts.ts from spec/openapi.json. Do not edit.

import type { APIPromise } from '../core/api-promise'
import { APIResource, pathParam } from '../core/client'
import type { RequestOptions } from '../core/http'
import type { PagePromise } from '../core/pagination'
import type { operations } from '../generated/schema'
import type { Customer } from '../generated/types'

export type CustomerListParams = NonNullable<operations['listCustomers']['parameters']['query']>
export type CustomerCreateParams = NonNullable<operations['createCustomer']['requestBody']>['content']['application/json']
export type CustomerUpdateParams = NonNullable<operations['updateCustomer']['requestBody']>['content']['application/json']

/** Customers: `invoiceai.customers`. */
export class Customers extends APIResource {
  /**
   * List customers.
   * Lists customers, newest first. Archived customers are left out unless `include_deleted=true`.
   * `GET /customers` · scope `clients:read`
   */
  list(params?: CustomerListParams, options?: RequestOptions): PagePromise<Customer> {
    return this._client._requestPage<Customer>({ method: 'GET', path: `/customers`, query: params, options, requiredScope: 'clients:read' })
  }

  /**
   * Create a customer.
   * Creates a customer to bill. Only `name` is required. Calls are not deduplicated: the same name twice makes two customers.
   * `POST /customers` · scope `clients:write` · idempotent (automatic key)
   */
  create(params: CustomerCreateParams, options?: RequestOptions): APIPromise<Customer> {
    return this._client._request<Customer>({ method: 'POST', path: `/customers`, body: params, options, requiredScope: 'clients:write' }, 'data')
  }

  /**
   * Retrieve a customer.
   * Returns a customer by `cus_…` id or UUID, including archived ones (`deleted: true`).
   * `GET /customers/{id}` · scope `clients:read`
   */
  retrieve(id: string, options?: RequestOptions): APIPromise<Customer> {
    return this._client._request<Customer>({ method: 'GET', path: `/customers/${pathParam('id', id)}`, options, requiredScope: 'clients:read' }, 'data')
  }

  /**
   * Update a customer.
   * Updates the fields you send and leaves the rest unchanged. Issued invoices keep the customer details they were billed with. No `Idempotency-Key` needed — repeating the call is harmless.
   * `PATCH /customers/{id}` · scope `clients:write`
   */
  update(id: string, params: CustomerUpdateParams, options?: RequestOptions): APIPromise<Customer> {
    return this._client._request<Customer>({ method: 'PATCH', path: `/customers/${pathParam('id', id)}`, body: params, options, requiredScope: 'clients:write' }, 'data')
  }

  /**
   * Archive a customer.
   * Archives a customer (`deleted: true`). Customers are never hard-deleted, because issued invoices must keep naming who they billed. Archived customers drop out of `GET /customers` but stay readable by id; archiving twice changes nothing.
   * `DELETE /customers/{id}` · scope `clients:write`
   */
  del(id: string, options?: RequestOptions): APIPromise<Customer> {
    return this._client._request<Customer>({ method: 'DELETE', path: `/customers/${pathParam('id', id)}`, options, requiredScope: 'clients:write' }, 'data')
  }
}
