// Generated by scripts/sdk-gen/ts.ts from api-docs/openapi.json. Do not edit.

import { BaseClient } from '../core/client'
import { BusinessResource } from './business'
import { Customers } from './customers'
import { Products } from './products'
import { Prices } from './prices'
import { Invoices } from './invoices'
import { InvoiceItems } from './invoice-items'
import { WebhookEndpoints } from './webhook-endpoints'

export { BusinessResource } from './business'
export { Customers } from './customers'
export type { CustomerListParams, CustomerCreateParams, CustomerUpdateParams } from './customers'
export { Products } from './products'
export type { ProductListParams, ProductCreateParams, ProductUpdateParams } from './products'
export { Prices } from './prices'
export type { PriceListParams, PriceCreateParams, PriceUpdateParams } from './prices'
export { Invoices } from './invoices'
export type { InvoiceListParams, InvoiceCreateParams, InvoiceUpdateParams, InvoiceSendParams, InvoiceSendResult, InvoicePayParams, InvoiceVoidParams, InvoicePdfParams } from './invoices'
export { InvoiceItems } from './invoice-items'
export type { InvoiceItemListParams, InvoiceItemCreateParams, InvoiceItemDeleteParams } from './invoice-items'
export { WebhookEndpoints } from './webhook-endpoints'
export type { WebhookEndpointCreateParams, WebhookEndpointCreateResult } from './webhook-endpoints'

/** The client with every API resource attached. `InvoiceAI` extends this. */
export class InvoiceAIResources extends BaseClient {
  /** Business. */
  readonly business: BusinessResource = new BusinessResource(this)
  /** Customers. */
  readonly customers: Customers = new Customers(this)
  /** Products. */
  readonly products: Products = new Products(this)
  /** Prices. */
  readonly prices: Prices = new Prices(this)
  /** Invoices. */
  readonly invoices: Invoices = new Invoices(this)
  /** Invoice items. */
  readonly invoiceItems: InvoiceItems = new InvoiceItems(this)
  /** Webhook endpoints. */
  readonly webhookEndpoints: WebhookEndpoints = new WebhookEndpoints(this)
}
