// Generated by scripts/sdk-gen/ts.ts from api-docs/openapi.json. Do not edit.

import type { APIPromise } from '../core/api-promise'
import { APIResource, pathParam } from '../core/client'
import type { RequestOptions } from '../core/http'
import type { PagePromise } from '../core/pagination'
import type { operations } from '../generated/schema'
import type { Invoice, InvoiceItem } from '../generated/types'

export type InvoiceItemListParams = NonNullable<operations['listInvoiceItems']['parameters']['query']>
export type InvoiceItemCreateParams = NonNullable<operations['createInvoiceItem']['requestBody']>['content']['application/json']
export type InvoiceItemDeleteParams = NonNullable<operations['deleteInvoiceItem']['parameters']['query']>

/** Invoice items: `invoiceai.invoiceItems`. */
export class InvoiceItems extends APIResource {
  /**
   * List invoice items.
   * Returns every line of one invoice, in order (not paginated). `invoice` is required.
   * `GET /invoice-items` · scope `invoices:read`
   */
  list(params: InvoiceItemListParams, options?: RequestOptions): PagePromise<InvoiceItem> {
    return this._client._requestPage<InvoiceItem>({ method: 'GET', path: `/invoice-items`, query: params, options, requiredScope: 'invoices:read' })
  }

  /**
   * Add an invoice item.
   * Appends one line to a draft: either a `price`, or `description` + `unit_amount`. Totals are recomputed, so the response is the whole invoice; every line gets a new id. Finalized invoices return `409`. Emits `invoice.updated`.
   * `POST /invoice-items` · scope `invoices:write` · idempotent (automatic key)
   */
  create(params: InvoiceItemCreateParams, options?: RequestOptions): APIPromise<Invoice> {
    return this._client._request<Invoice>({ method: 'POST', path: `/invoice-items`, body: params, options, requiredScope: 'invoices:write' }, 'data')
  }

  /**
   * Retrieve an invoice item.
   * Returns one line by `ii_…` id or UUID, from any of your invoices.
   * `GET /invoice-items/{id}` · scope `invoices:read`
   */
  retrieve(id: string, options?: RequestOptions): APIPromise<InvoiceItem> {
    return this._client._request<InvoiceItem>({ method: 'GET', path: `/invoice-items/${pathParam('id', id)}`, options, requiredScope: 'invoices:read' }, 'data')
  }

  /**
   * Remove an invoice item.
   * Removes one line from a draft and returns the whole recomputed invoice. A draft always keeps at least one line (`409` for the last one); finalized invoices return `409`. Pass `invoice` to scope the lookup to one invoice. Emits `invoice.updated`.
   * `DELETE /invoice-items/{id}` · scope `invoices:write`
   */
  del(id: string, params?: InvoiceItemDeleteParams, options?: RequestOptions): APIPromise<Invoice> {
    return this._client._request<Invoice>({ method: 'DELETE', path: `/invoice-items/${pathParam('id', id)}`, query: params, options, requiredScope: 'invoices:write' }, 'data')
  }
}
