// Generated by scripts/sdk-gen/ts.ts from spec/openapi.json. Do not edit.

import type { APIPromise } from '../core/api-promise'
import { APIResource, pathParam } from '../core/client'
import { buildURL, type RequestOptions } from '../core/http'
import type { PagePromise } from '../core/pagination'
import type { operations } from '../generated/schema'
import type { Invoice, InvoiceEvent } from '../generated/types'

export type InvoiceListParams = NonNullable<operations['listInvoices']['parameters']['query']>
export type InvoiceCreateParams = NonNullable<operations['createInvoice']['requestBody']>['content']['application/json']
export type InvoiceUpdateParams = NonNullable<operations['updateInvoice']['requestBody']>['content']['application/json']
export type InvoiceSendParams = NonNullable<operations['sendInvoice']['requestBody']>['content']['application/json']
export type InvoiceSendResponse = operations['sendInvoice']['responses'][200]['content']['application/json']
export type InvoicePayParams = NonNullable<operations['payInvoice']['requestBody']>['content']['application/json']
export type InvoiceVoidParams = NonNullable<operations['voidInvoice']['requestBody']>['content']['application/json']
export type InvoicePdfParams = NonNullable<operations['retrieveInvoicePdf']['parameters']['query']>
export type InvoiceEventsParams = NonNullable<operations['listInvoiceEvents']['parameters']['query']>

/** Invoices: `invoiceai.invoices`. */
export class Invoices extends APIResource {
  /**
   * List invoices.
   * Lists invoices, newest first, without `lines`. `status=overdue` returns open invoices whose `due_date` is before today (UTC); `status=open` includes them. An unknown `customer` filter is a `404`.
   * `GET /invoices` · scope `invoices:read`
   */
  list(params?: InvoiceListParams, options?: RequestOptions): PagePromise<Invoice> {
    return this._client._requestPage<Invoice>({ method: 'GET', path: `/invoices`, query: params, options, requiredScope: 'invoices:read' })
  }

  /**
   * Create a draft invoice.
   * Creates a `draft` invoice for an existing customer. Each line is either a catalog `price` (its name, amount and tax rate fill in) or an ad-hoc `description` + `unit_amount`. Totals are computed server-side; `currency` defaults to your business currency.
   * `POST /invoices` · scope `invoices:write` · idempotent (automatic key)
   */
  create(params: InvoiceCreateParams, options?: RequestOptions): APIPromise<Invoice> {
    return this._client._request<Invoice>({ method: 'POST', path: `/invoices`, body: params, options, requiredScope: 'invoices:write' }, 'data')
  }

  /**
   * Retrieve an invoice.
   * Returns an invoice by `in_…` id or UUID, with its `lines`. `status` reads `overdue` when an open invoice is past its due date.
   * `GET /invoices/{id}` · scope `invoices:read`
   */
  retrieve(id: string, options?: RequestOptions): APIPromise<Invoice> {
    return this._client._request<Invoice>({ method: 'GET', path: `/invoices/${pathParam('id', id)}`, options, requiredScope: 'invoices:read' }, 'data')
  }

  /**
   * Update a draft invoice.
   * Updates a draft. Send only the fields to change; `items`, when sent, replaces every line (line ids change). Once finalized an invoice is frozen and this returns `409`. Emits `invoice.updated`.
   * `PATCH /invoices/{id}` · scope `invoices:write`
   */
  update(id: string, params: InvoiceUpdateParams, options?: RequestOptions): APIPromise<Invoice> {
    return this._client._request<Invoice>({ method: 'PATCH', path: `/invoices/${pathParam('id', id)}`, body: params, options, requiredScope: 'invoices:write' }, 'data')
  }

  /**
   * Delete a draft invoice.
   * Permanently deletes a draft. A finalized invoice cannot be deleted (`409`) — its number belongs to a gap-free series. Void it instead.
   * `DELETE /invoices/{id}` · scope `invoices:write`
   */
  del(id: string, options?: RequestOptions): APIPromise<void> {
    return this._client._request<void>({ method: 'DELETE', path: `/invoices/${pathParam('id', id)}`, options, requiredScope: 'invoices:write' }, 'void')
  }

  /**
   * Finalize an invoice.
   * Issues a draft: assigns the next number in your series (e.g. `INV-0042`) and moves it to `open`. The draft needs at least one line. Finalizing an invoice that already has a number returns it unchanged, so a retry never spends a second number. Does not email the customer — see `/send`. Emits `invoice.finalized`.
   * `POST /invoices/{id}/finalize` · scope `invoices:finalize` · idempotent (automatic key)
   */
  finalize(id: string, options?: RequestOptions): APIPromise<Invoice> {
    return this._client._request<Invoice>({ method: 'POST', path: `/invoices/${pathParam('id', id)}/finalize`, options, requiredScope: 'invoices:finalize' }, 'data')
  }

  /**
   * Send an invoice.
   * Emails the invoice PDF and a link to its public page to `to`, or else the customer email on the invoice. A draft is finalized first (no `invoices:finalize` scope needed). Open and paid invoices can be re-sent; void ones cannot.
   * `POST /invoices/{id}/send` · scope `invoices:send` · idempotent (automatic key)
   */
  send(id: string, params?: InvoiceSendParams, options?: RequestOptions): APIPromise<InvoiceSendResponse> {
    return this._client._request<InvoiceSendResponse>({ method: 'POST', path: `/invoices/${pathParam('id', id)}/send`, body: params, options, requiredScope: 'invoices:send' }, 'body')
  }

  /**
   * Mark an invoice paid.
   * Marks an `open` (or overdue) invoice paid outside Invoice-AI — no money moves. `paid_on` is an ISO 8601 date or timestamp (defaults to now); `reference` is up to 200 characters. Drafts, void and already-paid invoices return `409`. The response omits `lines`. Emits `invoice.paid`, with `reference` in its meta.
   * `POST /invoices/{id}/pay` · scope `payments:write` · idempotent (automatic key)
   */
  pay(id: string, params?: InvoicePayParams, options?: RequestOptions): APIPromise<Invoice> {
    return this._client._request<Invoice>({ method: 'POST', path: `/invoices/${pathParam('id', id)}/pay`, body: params, options, requiredScope: 'payments:write' }, 'data')
  }

  /**
   * Void an invoice.
   * Voids an `open` (or overdue) invoice. `reason` is required, up to 500 characters. The number stays on record, so the series has no gaps. A paid invoice cannot be voided (it needs a credit note) and a draft should be deleted instead — both `409`. The response omits `lines`. Emits `invoice.voided`.
   * `POST /invoices/{id}/void` · scope `invoices:finalize` · idempotent (automatic key)
   */
  void(id: string, params: InvoiceVoidParams, options?: RequestOptions): APIPromise<Invoice> {
    return this._client._request<Invoice>({ method: 'POST', path: `/invoices/${pathParam('id', id)}/void`, body: params, options, requiredScope: 'invoices:finalize' }, 'data')
  }

  /**
   * Download an invoice PDF.
   * Returns the PDF bytes (not a link), rendered on demand from the current invoice — drafts too, without a number. Served inline; pass `download=1` for `Content-Disposition: attachment`. Not cacheable.
   * `GET /invoices/{id}/pdf` · scope `invoices:read`
   */
  pdf(id: string, params?: InvoicePdfParams, options?: RequestOptions): APIPromise<ArrayBuffer> {
    return this._client._request<ArrayBuffer>({ method: 'GET', path: `/invoices/${pathParam('id', id)}/pdf`, query: params, options, accept: 'application/pdf', requiredScope: 'invoices:read' }, 'binary')
  }

  /** The absolute URL of `GET /invoices/{id}/pdf`. Fetching it still needs `Authorization: Bearer <key>`. */
  pdfUrl(id: string, params?: InvoicePdfParams): string {
    return buildURL(this._client.baseURL, `/invoices/${pathParam('id', id)}/pdf`, params)
  }

  /**
   * List invoice events.
   * Lists one invoice’s history, newest first: created, updated, finalized, emailed, viewed, downloaded, paid, voided. `invoice.viewed` and `invoice.downloaded` mean the customer opened the public link; each is recorded at most once per invoice every 10 minutes.
   * `GET /invoices/{id}/events` · scope `invoices:read`
   */
  events(id: string, params?: InvoiceEventsParams, options?: RequestOptions): PagePromise<InvoiceEvent> {
    return this._client._requestPage<InvoiceEvent>({ method: 'GET', path: `/invoices/${pathParam('id', id)}/events`, query: params, options, requiredScope: 'invoices:read' })
  }
}
