// Generated by scripts/sdk-gen/ts.ts from api-docs/openapi.json. Do not edit.

import type { APIPromise } from '../core/api-promise'
import { APIResource, pathParam } from '../core/client'
import { buildURL, type RequestOptions } from '../core/http'
import type { PagePromise } from '../core/pagination'
import type { operations } from '../generated/schema'
import type { Invoice, InvoiceEvent } from '../generated/types'

export type InvoiceListParams = NonNullable<operations['listInvoices']['parameters']['query']>
export type InvoiceCreateParams = NonNullable<operations['createInvoice']['requestBody']>['content']['application/json']
export type InvoiceUpdateParams = NonNullable<operations['updateInvoice']['requestBody']>['content']['application/json']
export type InvoiceSendParams = NonNullable<operations['sendInvoice']['requestBody']>['content']['application/json']
export type InvoiceSendResult = operations['sendInvoice']['responses'][200]['content']['application/json']['data']
export type InvoicePayParams = NonNullable<operations['payInvoice']['requestBody']>['content']['application/json']
export type InvoiceVoidParams = NonNullable<operations['voidInvoice']['requestBody']>['content']['application/json']
export type InvoicePdfParams = NonNullable<operations['retrieveInvoicePdf']['parameters']['query']>

/** Invoices: `invoiceai.invoices`. */
export class Invoices extends APIResource {
  /**
   * List invoices.
   * Returns invoices newest first, cursor-paginated, without `lines`. `status=overdue` works even though no invoice is stored as overdue — it selects open invoices past `due_date`. An unknown `customer` is a `404`.
   * `GET /invoices` · scope `invoices:read`
   */
  list(params?: InvoiceListParams, options?: RequestOptions): PagePromise<Invoice> {
    return this._client._requestPage<Invoice>({ method: 'GET', path: `/invoices`, query: params, options, requiredScope: 'invoices:read' })
  }

  /**
   * Create a draft invoice.
   * Creates a `draft` for an existing customer. Each line is either a catalog `price` (description, amount and tax rate are borrowed from it) or an ad-hoc `description` + `unit_amount`. Totals are always computed server-side from the lines. The issue date is today; `currency` defaults to your business currency.
   * `POST /invoices` · scope `invoices:write` · idempotent (automatic key)
   */
  create(params: InvoiceCreateParams, options?: RequestOptions): APIPromise<Invoice> {
    return this._client._request<Invoice>({ method: 'POST', path: `/invoices`, body: params, options, requiredScope: 'invoices:write' }, 'data')
  }

  /**
   * Retrieve an invoice.
   * Returns one invoice by `in_…` id or UUID, with its `lines`. `status` reflects `overdue` at the moment of reading.
   * `GET /invoices/{id}` · scope `invoices:read`
   */
  retrieve(id: string, options?: RequestOptions): APIPromise<Invoice> {
    return this._client._request<Invoice>({ method: 'GET', path: `/invoices/${pathParam('id', id)}`, options, requiredScope: 'invoices:read' }, 'data')
  }

  /**
   * Update a draft invoice.
   * Drafts only. Merges the fields you send over the stored draft; `items`, when sent, replaces every line (omit it to keep them). `customer` is required. Totals are recomputed and line ids change. Once finalized an invoice is frozen — the customer may already have the PDF — and this returns `409`. Emits `invoice.updated`.
   * `PATCH /invoices/{id}` · scope `invoices:write`
   */
  update(id: string, params: InvoiceUpdateParams, options?: RequestOptions): APIPromise<Invoice> {
    return this._client._request<Invoice>({ method: 'PATCH', path: `/invoices/${pathParam('id', id)}`, body: params, options, requiredScope: 'invoices:write' }, 'data')
  }

  /**
   * Delete a draft invoice.
   * Permanently deletes a draft. A finalized invoice can never be deleted — its number belongs to a consecutive series, and a gap reads as a hidden sale. Void it instead.
   * `DELETE /invoices/{id}` · scope `invoices:write`
   */
  del(id: string, options?: RequestOptions): APIPromise<void> {
    return this._client._request<void>({ method: 'DELETE', path: `/invoices/${pathParam('id', id)}`, options, requiredScope: 'invoices:write' }, 'void')
  }

  /**
   * Finalize an invoice.
   * Assigns the next permanent number in your series (e.g. `INV-0042`) and moves the draft to `open`. The draft must have at least one line. Finalizing an invoice that already has a number returns it unchanged with the same number — a retry can never burn a second one. Does not email the customer (see `/send`). Emits `invoice.finalized`.
   * `POST /invoices/{id}/finalize` · scope `invoices:finalize` · idempotent (automatic key)
   */
  finalize(id: string, options?: RequestOptions): APIPromise<Invoice> {
    return this._client._request<Invoice>({ method: 'POST', path: `/invoices/${pathParam('id', id)}/finalize`, options, requiredScope: 'invoices:finalize' }, 'data')
  }

  /**
   * Send an invoice.
   * Emails the invoice PDF and a link to the public invoice page, via Resend, to `to` or else the customer email recorded on the invoice. A draft is finalized first (this scope covers that — `invoices:finalize` is not needed). Open and paid invoices can be re-sent; void ones cannot.
   * `POST /invoices/{id}/send` · scope `invoices:send` · idempotent (automatic key)
   */
  send(id: string, params?: InvoiceSendParams, options?: RequestOptions): APIPromise<InvoiceSendResult> {
    return this._client._request<InvoiceSendResult>({ method: 'POST', path: `/invoices/${pathParam('id', id)}/send`, body: params, options, requiredScope: 'invoices:send' }, 'data')
  }

  /**
   * Mark an invoice paid.
   * Records that an `open` (or overdue) invoice was paid outside Invoice-AI — no money moves. Drafts, void and already-paid invoices return `409`. Sets `paid_at` and `amount_due: 0`. The response omits `lines`. Emits `invoice.paid`, with `reference` in the event meta.
   * `POST /invoices/{id}/pay` · scope `payments:write` · idempotent (automatic key)
   */
  pay(id: string, params?: InvoicePayParams, options?: RequestOptions): APIPromise<Invoice> {
    return this._client._request<Invoice>({ method: 'POST', path: `/invoices/${pathParam('id', id)}/pay`, body: params, options, requiredScope: 'payments:write' }, 'data')
  }

  /**
   * Void an invoice.
   * Voids an `open` (or overdue) invoice with a reason. The number stays on the record — an auditor seeing 0041 then 0043 needs to find 0042 voided, not missing. A paid invoice cannot be voided (it needs a credit note); a draft should be deleted instead. The response omits `lines`. Emits `invoice.voided`.
   * `POST /invoices/{id}/void` · scope `invoices:finalize` · idempotent (automatic key)
   */
  void(id: string, params: InvoiceVoidParams, options?: RequestOptions): APIPromise<Invoice> {
    return this._client._request<Invoice>({ method: 'POST', path: `/invoices/${pathParam('id', id)}/void`, body: params, options, requiredScope: 'invoices:finalize' }, 'data')
  }

  /**
   * Download an invoice PDF.
   * Returns the PDF bytes (not a link), rendered on demand from the current invoice, so it is always up to date. Works for drafts too (without a number). Served inline; pass `download=1` for `Content-Disposition: attachment`. Not cacheable (`Cache-Control: private, no-store`).
   * `GET /invoices/{id}/pdf` · scope `invoices:read`
   */
  pdf(id: string, params?: InvoicePdfParams, options?: RequestOptions): APIPromise<ArrayBuffer> {
    return this._client._request<ArrayBuffer>({ method: 'GET', path: `/invoices/${pathParam('id', id)}/pdf`, query: params, options, accept: 'application/pdf', requiredScope: 'invoices:read' }, 'binary')
  }

  /** The absolute URL of `GET /invoices/{id}/pdf`. Fetching it still needs `Authorization: Bearer <key>`. */
  pdfUrl(id: string, params?: InvoicePdfParams): string {
    return buildURL(this._client.baseURL, `/invoices/${pathParam('id', id)}/pdf`, params)
  }

  /**
   * List invoice events.
   * Returns the full history of one invoice, newest first (not paginated): created, updated, finalized, emailed, viewed, downloaded, paid, voided. `invoice.viewed` and `invoice.downloaded` are recorded when the customer opens the public link — the way to tell they actually looked at it.
   * `GET /invoices/{id}/events` · scope `invoices:read`
   */
  events(id: string, options?: RequestOptions): PagePromise<InvoiceEvent> {
    return this._client._requestPage<InvoiceEvent>({ method: 'GET', path: `/invoices/${pathParam('id', id)}/events`, options, requiredScope: 'invoices:read' })
  }
}
