// Generated by scripts/sdk-gen/ts.ts from api-docs/openapi.json. Do not edit.

import type { APIPromise } from '../core/api-promise'
import { APIResource, pathParam } from '../core/client'
import type { RequestOptions } from '../core/http'
import type { PagePromise } from '../core/pagination'
import type { operations } from '../generated/schema'
import type { Price } from '../generated/types'

export type PriceListParams = NonNullable<operations['listPrices']['parameters']['query']>
export type PriceCreateParams = NonNullable<operations['createPrice']['requestBody']>['content']['application/json']
export type PriceUpdateParams = NonNullable<operations['updatePrice']['requestBody']>['content']['application/json']

/** Prices: `invoiceai.prices`. */
export class Prices extends APIResource {
  /**
   * List prices.
   * Returns prices newest first, cursor-paginated, optionally filtered by product, active flag, currency or type. An unknown `product` is a `404`, not an empty page.
   * `GET /prices` · scope `products:read`
   */
  list(params?: PriceListParams, options?: RequestOptions): PagePromise<Price> {
    return this._client._requestPage<Price>({ method: 'GET', path: `/prices`, query: params, options, requiredScope: 'products:read' })
  }

  /**
   * Create a price.
   * Adds a price to a product. `unit_amount` is integer minor units. A `recurring` price needs `recurring.interval`; it is stored for reporting — nothing auto-bills yet.
   * `POST /prices` · scope `products:write` · idempotent (automatic key)
   */
  create(params: PriceCreateParams, options?: RequestOptions): APIPromise<Price> {
    return this._client._request<Price>({ method: 'POST', path: `/prices`, body: params, options, requiredScope: 'products:write' }, 'data')
  }

  /**
   * Retrieve a price.
   * Returns one price by `price_…` id or UUID, whether active or archived.
   * `GET /prices/{id}` · scope `products:read`
   */
  retrieve(id: string, options?: RequestOptions): APIPromise<Price> {
    return this._client._request<Price>({ method: 'GET', path: `/prices/${pathParam('id', id)}`, options, requiredScope: 'products:read' }, 'data')
  }

  /**
   * Update a price.
   * Updates the fields you send and leaves the rest unchanged. The parent product cannot change — sending `product` is a `422`; create a new price instead. Lines on finalized invoices keep the amount they were billed at; a draft with a line from this price picks up the change the next time it is saved.
   * `PATCH /prices/{id}` · scope `products:write`
   */
  update(id: string, params: PriceUpdateParams, options?: RequestOptions): APIPromise<Price> {
    return this._client._request<Price>({ method: 'PATCH', path: `/prices/${pathParam('id', id)}`, body: params, options, requiredScope: 'products:write' }, 'data')
  }

  /**
   * Archive a price.
   * Sets `active: false`. The price is not deleted, because invoice lines may reference it. Archiving an archived price succeeds and changes nothing. Restore with `PATCH` and `active: true`.
   * `DELETE /prices/{id}` · scope `products:write`
   */
  archive(id: string, options?: RequestOptions): APIPromise<Price> {
    return this._client._request<Price>({ method: 'DELETE', path: `/prices/${pathParam('id', id)}`, options, requiredScope: 'products:write' }, 'data')
  }
}
