// Generated by scripts/sdk-gen/ts.ts from api-docs/openapi.json. Do not edit.

import type { APIPromise } from '../core/api-promise'
import { APIResource, pathParam } from '../core/client'
import type { RequestOptions } from '../core/http'
import type { PagePromise } from '../core/pagination'
import type { operations } from '../generated/schema'
import type { Product } from '../generated/types'

export type ProductListParams = NonNullable<operations['listProducts']['parameters']['query']>
export type ProductCreateParams = NonNullable<operations['createProduct']['requestBody']>['content']['application/json']
export type ProductUpdateParams = NonNullable<operations['updateProduct']['requestBody']>['content']['application/json']

/** Products: `invoiceai.products`. */
export class Products extends APIResource {
  /**
   * List products.
   * Returns products newest first, cursor-paginated. Archived products are included unless you filter with `active`.
   * `GET /products` · scope `products:read`
   */
  list(params?: ProductListParams, options?: RequestOptions): PagePromise<Product> {
    return this._client._requestPage<Product>({ method: 'GET', path: `/products`, query: params, options, requiredScope: 'products:read' })
  }

  /**
   * Create a product.
   * Creates a product. Add one or more prices to it with `POST /prices` before billing it.
   * `POST /products` · scope `products:write` · idempotent (automatic key)
   */
  create(params: ProductCreateParams, options?: RequestOptions): APIPromise<Product> {
    return this._client._request<Product>({ method: 'POST', path: `/products`, body: params, options, requiredScope: 'products:write' }, 'data')
  }

  /**
   * Retrieve a product.
   * Returns one product by `prod_…` id or UUID, whether active or archived.
   * `GET /products/{id}` · scope `products:read`
   */
  retrieve(id: string, options?: RequestOptions): APIPromise<Product> {
    return this._client._request<Product>({ method: 'GET', path: `/products/${pathParam('id', id)}`, options, requiredScope: 'products:read' }, 'data')
  }

  /**
   * Update a product.
   * Updates the fields you send and leaves the rest unchanged — omitted fields are never reset to defaults. Send `active: true` to restore an archived product. Finalized invoices keep the line descriptions they were issued with.
   * `PATCH /products/{id}` · scope `products:write`
   */
  update(id: string, params: ProductUpdateParams, options?: RequestOptions): APIPromise<Product> {
    return this._client._request<Product>({ method: 'PATCH', path: `/products/${pathParam('id', id)}`, body: params, options, requiredScope: 'products:write' }, 'data')
  }

  /**
   * Archive a product.
   * Sets `active: false`. The product is not deleted — its prices and the invoice lines that reference it stay intact. Archiving an archived product succeeds and changes nothing. Restore with `PATCH` and `active: true`.
   * `DELETE /products/{id}` · scope `products:write`
   */
  archive(id: string, options?: RequestOptions): APIPromise<Product> {
    return this._client._request<Product>({ method: 'DELETE', path: `/products/${pathParam('id', id)}`, options, requiredScope: 'products:write' }, 'data')
  }
}
