// Generated by scripts/sdk-gen/ts.ts from api-docs/openapi.json. Do not edit.

import type { APIPromise } from '../core/api-promise'
import { APIResource, pathParam } from '../core/client'
import type { RequestOptions } from '../core/http'
import type { PagePromise } from '../core/pagination'
import type { operations } from '../generated/schema'
import type { WebhookEndpoint } from '../generated/types'

export type WebhookEndpointCreateParams = NonNullable<operations['createWebhookEndpoint']['requestBody']>['content']['application/json']
export type WebhookEndpointCreateResult = operations['createWebhookEndpoint']['responses'][201]['content']['application/json']['data']

/** Webhook endpoints: `invoiceai.webhookEndpoints`. */
export class WebhookEndpoints extends APIResource {
  /**
   * List webhook endpoints.
   * Returns all your webhook endpoints, newest first (not paginated). Signing secrets are never included — only once, at creation.
   * `GET /webhook-endpoints` · scope `webhooks:manage`
   */
  list(options?: RequestOptions): PagePromise<WebhookEndpoint> {
    return this._client._requestPage<WebhookEndpoint>({ method: 'GET', path: `/webhook-endpoints`, options, requiredScope: 'webhooks:manage' })
  }

  /**
   * Create a webhook endpoint.
   * Registers an https URL to receive events. The response carries the signing `secret` (`whsec_…`) — the only time it is returned, so store it. The URL must use https and must not resolve to a private, loopback or link-local address.
   * `POST /webhook-endpoints` · scope `webhooks:manage` · idempotent (automatic key)
   */
  create(params: WebhookEndpointCreateParams, options?: RequestOptions): APIPromise<WebhookEndpointCreateResult> {
    return this._client._request<WebhookEndpointCreateResult>({ method: 'POST', path: `/webhook-endpoints`, body: params, options, requiredScope: 'webhooks:manage' }, 'data')
  }

  /**
   * Delete a webhook endpoint.
   * Permanently deletes the endpoint; no further deliveries are made to it. Deleting it again is a `404`, not a silent success — that usually means you are working from a stale list.
   * `DELETE /webhook-endpoints/{id}` · scope `webhooks:manage`
   */
  del(id: string, options?: RequestOptions): APIPromise<void> {
    return this._client._request<void>({ method: 'DELETE', path: `/webhook-endpoints/${pathParam('id', id)}`, options, requiredScope: 'webhooks:manage' }, 'void')
  }
}
